### ISSUE TITLE
nvd update issue

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#1034]
**Describe the bug**
Right now the nvd data update is not working.

**To Reproduce**
1. EMBA installation default mode
2. $ sudo git pull
3. See error

**Expected behavior**
Maybe it is just a temporary problem and not connected to emba.

**Screenshots**
![kép](https://github.com/e-m-b-a/emba/assets/98665813/29e642ec-e144-4b79-9f76-e754a437342e)

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.4
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Comment by m-1-k-3** [comment]
My fault ... One moment

**Comment by torabi12** [comment]
Works again:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/572b51ca-65ed-47ca-8a27-9f510ff75ec3)

Thank you.

**Comment by m-1-k-3** [comment]
Yea we had this some time ago. The update process was a bit more complex a while ago because of the cve-checker. Now, the update process is quite simple and just a bunch of documented commands (see [here](https://github.com/e-m-b-a/emba/wiki/EMBA-update)). So, just put them again in a little script or cronjob and you are ready to go.

**Comment by m-1-k-3** [comment]
Please reopen if needed

**Comment by m-1-k-3** [comment]
> emba used to have a script which made the update process. Now we update emba, the database and the docker images with separate commands. It works fine, but a very short script would be very useful to go through the entire update process and not one by one manually.

btw you are aware of the `-U` option?

**Comment by torabi12** [comment]
Thank you, I was not aware of it :(
I did one by one, the git pull for emba, for the DB and for the docker as well. Now it is much better:) Great!
