### ISSUE TITLE
New Kali Linux 2024.01 available

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#1058]
New Kali Linux is out: https://www.kali.org/blog/kali-linux-2024-1-release/

We need to test EMBA on it

**Testcases:**

Testfirmware: [DLink DIR300](https://ftp.dlink.de/dir/dir-300/archive/driver_software/DIR-300_fw_revb_214b01_ALL_de_20130206.zip)

- [ ] Default/docker installation working with current docker image
  - [x] `./installer.sh -d` finished without errors
  - [x] dependency check (`./emba -d 1`)
  - [x] EMBA run with profile quick-scan
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [ ] EMBA run with profile full-scan in strict mode (-S)
- [ ] Docker base image build 
  - [x] `sudo docker-compose build --no-cache --pull` finished without errors
  - [x] dependency check (`./emba -d 2`)
  - [x] EMBA run with profile quick-scan
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [ ] EMBA run with profile full-scan in strict mode (-S)
- [x] Full installation working on Kali Linux
  - [x] `./installer.sh -F` finished without errors
  - [x] dependency check (`./emba -d 1`)
  - [x] EMBA run in dev mode with options -s -z -S -D -E -t -W -Q
  - [x] EMBA run in dev mode with options -s -z -S -D, -c, -E, -t, -W -Q

**Comment by d4op** [comment]
Kali 2024.1

./emba -d 1

ERROR:
GHIDRA - not ok
Missing GHIDRA - check your installation

CHECK:
apt install ghidra                         
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ghidra is already the newest version (11.0+ds-0kali1).




ERROR:                                                                                                                                                           
Looks like your docker container is outdated - please update your base image: sudo docker pull embeddedanalyzer/emba'.                                      
ERROR: 1                                                                            

CHECK:
sudo docker pull embeddedanalyzer/emba
Using default tag: latest
latest: Pulling from embeddedanalyzer/emba
Digest: sha256:eb64476d7e42d1a101bd041dd9a48fd0c9f314195214ceb6f73def86a51d8108
Status: Image is up to date for embeddedanalyzer/emba:latest
docker.io/embeddedanalyzer/emba:latest



i get this 2 errors which are false.

**Comment by torabi12** [comment]
I am doing the last full installation section.

Install was ok:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/b0e1a511-062c-407d-9a94-e35f2d274c25)

Dependency check was also error free:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/6910e801-0bd6-4799-bf7c-db0ec1f43f4a)

I try to do the last 2 items.

**Comment by m-1-k-3** [comment]
cool ... full install is always the most challenging as it is nearly not tested in between the releases ... looking forward to the results

**Comment by torabi12** [comment]
3rd was OK:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/dce52209-b3d8-49ef-ac71-dafbf58c4b3e)

with this start command:

`$ sudo ./emba -l ~/DIR300 -f ~/DIR300B5_FW214WWB01.bin -s -z -S -D -E -t -W -Q -X 2.14B01 -Y Dlink -Z DIR300 -N DIR300B5_FW214WWB01.bin`

Running the last item.

**Comment by torabi12** [comment]
Last test is also ended:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/57e0f115-2b88-400c-a20f-7c8d9b97559c)

**Comment by m-1-k-3** [comment]
@torabi12 thx for supporting these tests

**Comment by torabi12** [comment]
> @torabi12 thx for supporting these tests

You are welcome. :)
