### ISSUE TITLE
-b displays only the latest txt

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#1079]
**Describe the bug**
`./emba -b `used to display random logo from emba/config/banner/ folder. If I execute now only the latest ICS edition logo is displayed. Not a problem in itself, but it may have an effect on other things.

**To Reproduce**
1. EMBA installation default mode
2. `./emba -b`
3. See only an ICS logo.

**Expected behavior**
Random logo should be displayed as before.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.4
- EMBA version: v1.4.0 / current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**
N/A

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
This is just because the current github version is tagged as release

https://github.com/e-m-b-a/emba/blob/3eb3f96167ebad56592e72169caa84178917dd2c/helpers/helpers_emba_defaults.sh#L21

The behavior should automatically change on one of the next PR

**Comment by torabi12** [comment]
Thank you!
