### ISSUE TITLE
Status bar without day count

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#1083]
**Describe the bug**
Status bar shows only hours, if the test is longer than a day it will start again from 0:00:00.
Cosmetic issue, which is only valid for very long executions.

**To Reproduce**
1. EMBA installation default mode
2. Start EMBA with the following parameters: sudo ./emba.sh -p ./scan-profiles/default-scan.emba
4. wait 24:00:01
5. See error

**Expected behavior**
Status bar should count days as well.

**Screenshots**
![image](https://github.com/e-m-b-a/emba/assets/98665813/cd598c87-b9fc-4774-98c4-575c91ebecb3)

**Desktop (please complete the following information):**
- OS: Kali Linux 2024.1
- EMBA version: v1.4.0
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
The past hit us again ... I think we had some similar issue a while back ;) Thanks for reporting
