### ISSUE TITLE
Specify file system instead of firmware

### ISSUE THREAD

**Issue by lucky-zh** [e-m-b-a/emba#1125]
**Is your feature request related to a problem? Please describe.**
Can I use EMBA to directly specify the file system obtained by unpacking the firmware for analysis? Because some firmware is encrypted, specific decryption scripts are required.

**Comment by m-1-k-3** [comment]
Hi @lucky-zh 

 after extracting the firmware manually to a dedicated directory you should be able to just specify this directory as firmware path with the `-f` parameter.

**Comment by lucky-zh** [comment]
Okay, thank you. Maybe it would be better to add an explanation of the -f parameter in usage.
