### ISSUE TITLE
installer.sh failing with non-english locale

### ISSUE THREAD

**Issue by beruhan** [e-m-b-a/emba#1162]
To use EMBA, some applications must be installed and some data (database for CVS for example) downloaded and parsed.

These applications will be installed/updated:

jq
Description: lightweight and flexible command-line JSON processor
Download-Size: 52,5 kB
Error detected - status code 1
Command: echo -e "Command: $ORANGE$BASH_COMMAND$NC"
Location: ./installer/helpers.sh, line 64
Stack Trace:
[1] print_tool_info(): ./installer/helpers.sh, line 64 -> print_tool_info jq 1
[2] I01_default_apps_host(): ./installer/I01_default_apps_host.sh, line 24 -> I01_default_apps_host
[3] main(): ./installer.sh, line 182 -> main -d

Important: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues

locale comand output:
![image](https://github.com/e-m-b-a/emba/assets/7598892/5bc07db6-c591-41d0-80e7-96fa30ee3249)

**Comment by m-1-k-3** [comment]
Thank you for reporting. Is it working the following:
```
LANG=en ./installer.sh -d
```
or probably as non root
```
LANG=en sudo -E ./installer.sh -d
```

**Comment by beruhan** [comment]
the same also:
![image](https://github.com/e-m-b-a/emba/assets/7598892/52716f11-4fce-4857-9ad4-fefc55189bd1)
![image](https://github.com/e-m-b-a/emba/assets/7598892/97e7203c-9ee7-4c2e-ac1c-510fb7870e5b)

**Comment by m-1-k-3** [comment]
please use in default mode only the `-d` parameter. The other parameters are for building the EMBA docker image

**Comment by HoxhaEndri** [comment]
@beruhan I was able to reproduce the error and I found the issue: the variable `LC_ALL` is set to `zh_CN.UTF-8`. 
In `/etc/default/locale` comment the line, that sets the variable `LC_ALL`, save the file and then reboot. 
After the reboot, check with the command `locale`, that the `LC_ALL` is set to nothing, if it is the case, you should be able to install emba with `sudo ./installer.sh -d`.

**Comment by beruhan** [comment]
I want to build emba in my own docker.my docker file as fllows:
![image](https://github.com/e-m-b-a/emba/assets/7598892/66b6f03b-418d-4458-8cb0-2acd0ee65c22)
my locale file as fllows:
![image](https://github.com/e-m-b-a/emba/assets/7598892/a1baabf0-a22b-40e2-b827-2754941f9bc9)

**Comment by m-1-k-3** [comment]
the simple way is to checkout the EMBA repo, and building it with the following command:

```
sudo docker-compose build --no-cache --pull
```

**Comment by beruhan** [comment]
a new error occured as fllows:
![image](https://github.com/e-m-b-a/emba/assets/7598892/89c8c9ed-824b-4307-aa59-2a3b90033895)

**Comment by m-1-k-3** [comment]
Manual stepping through the installer will be tough ... please try to build it as shown here https://github.com/e-m-b-a/emba/issues/1162#issuecomment-2136645627

**Comment by beruhan** [comment]
that ok!
