### ISSUE TITLE
 Are we able to get the file system in the firmware?

### ISSUE THREAD

**Issue by zut-zyq** [e-m-b-a/emba#1174]
When using the EMBA tool to analyze the firmware, I saw that after the analysis was completed, the first thing I wanted was some relevant information about the firmware, including the firmware architecture, operating system, big and small endian, file system, etc. Among them, I checked All execution results show that no file system is found. Is it possible to add this function or did I not find it? Thanks

**Comment by BenediktMKuehne** [comment]
We need more info to be able to help you.
Please follow this [Issue template](https://github.com/e-m-b-a/emba/blob/master/.github%2FISSUE_TEMPLATE%2Fbug_report.md)

What command did you run&
Which firmware file?

**Comment by zut-zyq** [comment]
I used EMBA to detect a D-Link device and ran the command **./emba -l /log -f /firmware/DIR820LA1_FW100KRB08.bin -c** to perform the detection.
I want to find in the results what file system the firmware belongs to. For example, the **file system** of the firmware is **squashfs**. Does our tool have the function to specifically identify the file system of the firmware? Because I found that using tools such as binwalk cannot ensure that the file system of the firmware can be obtained.

**Comment by m-1-k-3** [comment]
Usually in /log/firmware

**Comment by m-1-k-3** [comment]
this DIR820 firmware looks quite good:

![image](https://github.com/e-m-b-a/emba/assets/497520/35bba81a-f184-4175-8cb4-58e49fb0bb45)

**Comment by zut-zyq** [comment]
> this DIR820 firmware looks quite good:
> 
> ![image](https://private-user-images.githubusercontent.com/497520/334023569-35bba81a-f184-4175-8cb4-58e49fb0bb45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTk4MDksIm5iZiI6MTcxNjc5OTUwOSwicGF0aCI6Ii80OTc1MjAvMzM0MDIzNTY5LTM1YmJhODFhLWYxODQtNDE3NS04Y2I0LTU4ZTQ5ZmIwYmI0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwODQ1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzUwMzZkZTM3MTk4OTljMjIyNTc3NDRkMTJlZDM2ZGE1YTM5YWZhMjVlZTg4ZDQxNzkxZTBhNzIwYTc3ZGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NwR9Ul3N1nwNxyZWHgwrzRUpcnohez1rcQwmPPVBM2U)

Why does it execute the p40 module?

**Comment by m-1-k-3** [comment]
> Why does it execute the p40 module?

just for logging as it has not detected DIJ firmware image
