### ISSUE TITLE
The s110 module cannot be executed normally

### ISSUE THREAD

**Issue by zut-zyq** [e-m-b-a/emba#1175]
I encountered some problems in the s110 module and emba.log during use.
1. I execute **EMBA="." FIRMWARE=/firmware LOG=/log docker-compose run emba** in the EMBA root directory
2. enter docker and execute **./emba -l /log -f /firmware -i -c -t -P 8 -T 8** , and wait for the execution to complete. 
3. After checking the s110 module log, the log shows that yara is not installed. But the yara environment is installed in the docker environment.
![image](https://github.com/e-m-b-a/emba/assets/80234460/4d9eed9e-3973-4e18-ae53-b97b97e23a7c)
![image](https://github.com/e-m-b-a/emba/assets/80234460/b2b2e30c-442b-44d7-9f98-f05b40185f5b)
4. Using EMBA outside docker has the same problem.
5. And by checking emba.log, I found that I did not set the -e parameter, but the s115 module call record appeared in the log, but only the end call of the module was recorded, and the start call of the module was not recorded.
![image](https://github.com/e-m-b-a/emba/assets/80234460/3e1c04c2-d4c5-4804-a513-b5a5a55d2c13)

**Comment by m-1-k-3** [comment]
I recommend start EMBA not from the container. The emba startup script is designed to ensure everything is in place and should be working (including dependencies, auto threading and so on).

Please try it from the outside of the container:
```
 ./emba -l /log -f /firmware -p ./scan-profiles/default-scan.emba
```

**Comment by m-1-k-3** [comment]
btw. to enable yara tests you need to enable it in the default settings [here](https://github.com/e-m-b-a/emba/blob/7e5cb348c8c5ddd7353e44ffae8e4b885189ca13/helpers/helpers_emba_defaults.sh#L86) or as shown in the scanning profile [here](https://github.com/e-m-b-a/emba/blob/7e5cb348c8c5ddd7353e44ffae8e4b885189ca13/scan-profiles/full-scan.emba#L25)

**Comment by zut-zyq** [comment]
> btw. to enable yara tests you need to enable it in the default settings [here](https://github.com/e-m-b-a/emba/blob/7e5cb348c8c5ddd7353e44ffae8e4b885189ca13/helpers/helpers_emba_defaults.sh#L86) or as shown in the scanning profile [here](https://github.com/e-m-b-a/emba/blob/7e5cb348c8c5ddd7353e44ffae8e4b885189ca13/scan-profiles/full-scan.emba#L25)

Thanks！

**Comment by m-1-k-3** [comment]
As the note from the module is somehow wrong I will update it for better understanding.
