### ISSUE TITLE
docker image question

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#1192]
**Describe the bug**

During the install I got 1.4.1c docker image:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/23765569-f76d-4de5-9c6a-b7b5ffb33f46)

After I ran a dependency check and it displayed an update for docker:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/661df101-ee85-40fe-b11a-5cb551cb44fb)

I used the update:
$ sudo ./emba -U

and this was downloading the latest:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/d3c7c413-8833-4ce1-92a1-36872a83b3ae)

Now I have these on the VM:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/76d6f612-1234-4b4d-b26c-a4966cb2501e)

I don't understand why downloading the 3 months old when the 2 days are already available.

**To Reproduce**
1. EMBA installation default mode
2. sudo ./emba -d 1
3. sudo ./emba -U
4. sudo docker image ls
5. See the problem.

**Expected behavior**
The latest should be the latest.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: Kali Linux 2024.2
- EMBA version: current master branch
- Installation method: default with up to date docker image ???

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
Thx for pointing to this issue. I need to Tag the 1.4.1c to latest. Will do this tomorrow

**Comment by m-1-k-3** [comment]
should be solved by now ... could you please check

**Comment by torabi12** [comment]
@work I have an older version of emba running on Kali 2024.1 and the -U just shows the status:

![image](https://github.com/e-m-b-a/emba/assets/98665813/7c3aff1d-c825-4d93-b0df-d89f4e8a295c)

I will try on the latest release @home evening, but it will be fine for sure.

**Comment by torabi12** [comment]
After the installation I ran emba -U and I got this:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/c2f306db-912b-4cf1-802a-d9ff80147d34)

These are on the VM:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/e8415261-5e23-4129-984b-7c0462f8fdd6)

**Comment by m-1-k-3** [comment]
looks not too bad. With the next PR we will include the latest tag again in the installer and then I think it should be fine again.

**Comment by torabi12** [comment]
Thank you for your support!

**Comment by m-1-k-3** [comment]
should be fixed by now. Please do a check

**Comment by torabi12** [comment]
During the install:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/e3b3afe5-d664-4f76-af8c-b6b8d264dc4e)

after the install we have this:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/40d56e69-f3c1-4e10-82de-0bcbd7dd9168)

$ sudo ./emba -U shows these:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/278e64bb-9ee6-47bd-95cc-0fdbb4744b37)

I just don't understand why we have 1.4.1d and latest on the list, but the ID is the same so should be fine.

**Comment by m-1-k-3** [comment]
looking good ... thx fortesting
