### ISSUE TITLE
emba install error << when i start build the emba in docker with this command "sudo docker-compose build emba  " the install stop in 7/9 step  << please help me 

### ISSUE THREAD

**Issue by abdoqaidhaidar** [e-m-b-a/emba#1213]
![Screenshot 2024-07-02 114713](https://github.com/e-m-b-a/emba/assets/170963725/82fd7560-f450-47c2-b523-31d0d9bcef0b)

**Comment by m-1-k-3** [comment]
could be a connection issue. Last night the build was fine.

**Comment by m-1-k-3** [comment]
Tested another build manually and it was working as expected.

**Comment by abdoqaidhaidar** [comment]
ok now how i can solve this problem help me please

**Comment by m-1-k-3** [comment]
The first question that arises is why you want to build your own base image. We prebuild and test the default EMBA base image.
The next thing is that the image is currently building fine. We test it every day and I did another manual build which was also fine. I am very sorry but I can't help without being able reproducing it

**Comment by m-1-k-3** [comment]
please reopen if needed
