### ISSUE TITLE
cannot finish the installation

### ISSUE THREAD

**Issue by appelsinol** [e-m-b-a/emba#1235]
**Describe the bug**
I am currently trying to install them EMBA in Kali 2024.02, I cannot complete the installation. 

**To Reproduce**
After I runing sudo ./installer.sh -d, I cannot complete the installation. The screenshot is shown in the screenshot.

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/b7d81c70-3df9-4f1c-ba51-d4268ff7c4fc)

**Desktop (please complete the following information):**
- OS: Kali Linux 2024.02
- EMBA version: latest version
- Installation method: default method

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
This is usually based on some connection issues. Try to start the installation again. If it failes again you can also try to download the base image manually before starting the installer again:

```
docker pull embeddedanalyzer/emba:1.4.1e
```

**Comment by appelsinol** [comment]
Thanks. It seems that it has a connection issue. I have to manually download the image.

I used sudo ./installer.sh -c {embeddedanalyzer/emba:1.4.1e} to install, the following issue pops up:

![image](https://github.com/user-attachments/assets/58db3a27-157e-4e47-9601-b3f04cc028af)

I used sudo ./installer.sh -d -c {embeddedanalyzer/emba:1.4.1e} as suggested in the installation page, 

I encountered the following issue:
![image](https://github.com/user-attachments/assets/8b2d1ac1-6cc6-4c37-bd3f-2ba7352db022)

Could you help me on it?

**Comment by m-1-k-3** [comment]
why not just using the command from here https://github.com/e-m-b-a/emba/issues/1235#issuecomment-2228618689 and then run the installer just with -d parameter?

**Comment by quyifei** [comment]
I have the same issues. The reason looks that I am in China the connections to outside China is blocked😡 unfortunately.  I am still trying how to work around this issue.

**Comment by m-1-k-3** [comment]
please reopen if needed
