### ISSUE TITLE
Installation stopped

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#1247]
**Describe the bug**
Today the installation was not working for me:

![kép](https://github.com/user-attachments/assets/43f6cab9-bbda-40f3-845f-3267ec369d75)

**To Reproduce**
1. EMBA installation default mode
2. See error

**Expected behavior**
Should go on.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: e.g. Kali Linux 2024.2
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**
Is it OK on your side?

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
is the command "docker-compose" available?

**Comment by torabi12** [comment]
When the installer stops only the `docker-init` and the `docker-proxy` are available.

**Comment by m-1-k-3** [comment]
Is this some nightly build or the stable 2024.02 from Kali?

**Comment by torabi12** [comment]
Official 2024.2
https://cdimage.kali.org/kali-2024.2/kali-linux-2024.2-vmware-amd64.7z

**Comment by m-1-k-3** [comment]
looks as the docker-compose package is not available anymore. Probably we need to switch to pip

**Comment by m-1-k-3** [comment]
@torabi12 could you please check the linked PR #1248

**Comment by torabi12** [comment]
The installation went on and there weren't any error. After the install we have these:
```

$ docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by m-1-k-3** [comment]
Thank you for reporting

**Comment by torabi12** [comment]
I tried an EMBArk installation but I got similar issue:

![kép](https://github.com/user-attachments/assets/8811a76d-a1dc-4fc1-94b2-def48ef540d0)

I don't know what happened, it used to work witj Ubuntu 22.04.4
docker-compose is also missing from the server too.

:(

**Comment by m-1-k-3** [comment]
@BenediktMKuehne FYI
