### ISSUE TITLE
Issues： Missing NVD CVE database 

### ISSUE THREAD

**Issue by A-jian** [e-m-b-a/emba#1256]
I followed the installation steps and it said that the NVD CVE database was missing.
I reproduced the behavior, but it still doesn't work.

![1](https://github.com/user-attachments/assets/ca6c6089-f4b5-484b-83e4-41337ac78cbc)
![2](https://github.com/user-attachments/assets/13ff550b-aea2-44c3-b0e2-976ff8f70229)
![3](https://github.com/user-attachments/assets/45db76d8-f603-4297-bec3-c2720e45e451)

My Desktop (please complete the following information):

OS:  Kali Linux 2024.2 
EMBA version: v1.4.1 
Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
Are you using the stable version 1.4.1 or the latest github version? If you are using the stable version please try the latest GH version and check if the installation works then. If not we need to dig into this

**Comment by m-1-k-3** [comment]
Did a fresh Kali Installation which was working fine. Please try the latest Github master

**Comment by A-jian** [comment]
> Did a fresh Kali Installation which was working fine. Please try the latest Github master

Thanks for your help. I found that it was a problem with the installation source. For some network reasons, I changed the installation source of Kali. After I changed it to the original installation source, your method worked. Although there were some problems during the installation due to network problems, as shown in the figure. But after retrying several times, the installation was completed. Thanks again.
![捕获](https://github.com/user-attachments/assets/0374e4ae-6c85-4a0a-b873-016a51942730)

**Comment by m-1-k-3** [comment]
If you are experiencing network issues you can try to download the docker base image manually and also clone the nvd database manually. Afterwards, there are just a few packages to install

**Comment by A-jian** [comment]
> If you are experiencing network issues you can try to download the docker base image manually and also clone the nvd database manually. Afterwards, there are just a few packages to install

OK.I have successfully installed it by following the installation documentation.
