### ISSUE TITLE
Sed Error

### ISSUE THREAD

**Issue by seanog8** [e-m-b-a/emba#126]
I have the Error message which you can see in the screenshot. Im not sure if it came with my changes of my fork. If I remember right it is also appearing in the master branch. It is only in the console output, but not in the logfile.

![image](https://user-images.githubusercontent.com/43826380/122685215-3ecc1480-d20a-11eb-8df6-697c1d148f4e.png)

**Comment by seanog8** [comment]
Maybe you can check next time you run a scan if it is appearing for you as well. Otherwise I'll recheck it with a firmware-scan with the master branch soon.

**Comment by m-1-k-3** [comment]
Thanks for reporting. Have you activated the web-reporter? If so, could you please give it a run without the web reporter and check if the error also appears?

**Comment by p4cx** [comment]
Looks like a bug in the webreport (position wise) - I will check this in near future.

**Comment by seanog8** [comment]
Yes, I ran a small scan without webreport. It is not appearing there.
