### ISSUE TITLE
Bugs reported by reddit user geirha

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#129]
Multiple issues found by reddit user [geirha](https://www.reddit.com/user/geirha/) https://www.reddit.com/r/bash/comments/o2ib89/emba_an_open_source_firmware_analyzer_has/

**Comment by p4cx** [comment]
[First bug:](https://www.reddit.com/r/bash/comments/o2ib89/emba_an_open_source_firmware_analyzer_has/h27hqoe?utm_source=share&utm_medium=web2x&context=3) #127 
[Second bug:](https://www.reddit.com/r/bash/comments/o2ib89/emba_an_open_source_firmware_analyzer_has/h26op5w?utm_source=share&utm_medium=web2x&context=3)
[Third bug:](https://www.reddit.com/r/bash/comments/o2ib89/emba_an_open_source_firmware_analyzer_has/h26w2kj?utm_source=share&utm_medium=web2x&context=3)
