### ISSUE TITLE
Export all components found to CycloneDX SBOM

### ISSUE THREAD

**Issue by swenp76** [e-m-b-a/emba#1297]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
By now emba already exports a SBOM in CycloneDX format, but afaik only for components with vulnerabilities.
It would be great if emba could also export a SBOM  containing all components found, regardless their vulnerability status.
This way one could use the generated SBOM to monitor for upcoming CVEs, using e.g. OWASP Dependency Track, grype or other FOSS tools.

**Describe alternatives you've considered**
None

**Priority issue**
Are you already a [Sponsor]?
No

**Additional context**

![grafik](https://github.com/user-attachments/assets/a58fbefb-27a5-427a-bb52-b8cd272d051d)

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
I need to check on this. Will come back soon

**Comment by m-1-k-3** [comment]
Ok, I can reproduce this behavior and will look into it. Thanks for reporting

**Comment by m-1-k-3** [comment]
@swenp76 please give it a try here #1299

**Comment by swenp76** [comment]
> @swenp76 please give it a try here #1299
@m-1-k-3 
Ok, thanks. Will come back with feedback shortly

**Comment by m-1-k-3** [comment]
please reopen if not fixed
