### ISSUE TITLE
New Kali Linux 2024.3 is available

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#1300]
New Kali Linux is out: https://www.kali.org/blog/kali-linux-2024-3-release/

We need to test EMBA on it

**Testcases:**

Testfirmware: [DLink DIR300](https://ftp.dlink.de/dir/dir-300/archive/driver_software/DIR-300_fw_revb_214b01_ALL_de_20130206.zip)

- [x] Default/docker installation working with current docker image
  - [x] `./installer.sh -d` finished without errors
  - [x] dependency check (`./emba -d 1`)
  - [x] EMBA run with profile quick-scan
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)
- [x] Docker base image build
  - [x] `sudo docker-compose build --no-cache --pull` finished without errors
  - [x] dependency check (`./emba -d 2`)
  - [x] EMBA run with profile quick-scan
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)
- [ ] Full installation working on Kali Linux
  - [ ] `./installer.sh -F` finished without errors
  - [ ] dependency check (`./emba -d 1`)
  - [ ] EMBA run in dev mode with options -s -z -S -D -E -t -W -Q
  - [ ] EMBA run in dev mode with options -s -z -S -D, -c, -E, -t, -W -Q

On all tests check html report if it is correct and check for the emba_error.log

**Priority issue**
YES

**Comment by torabi12** [comment]
I am going to do the first section, default/docker installation tests...

**Comment by torabi12** [comment]
Default installation was OK:

![kép](https://github.com/user-attachments/assets/cf3a4f39-eb85-4e22-9dbd-6150757b4fbd)

Dependency check also:

![kép](https://github.com/user-attachments/assets/9580947f-9ad8-4195-b6c0-23147c53c6a1)

Quick-scan profile OK:

![kép](https://github.com/user-attachments/assets/979337ea-6ce3-4bf1-a2c4-b6610b7b1996)

Default-scan in strict mode also OK:

![kép](https://github.com/user-attachments/assets/a0a73f3b-9a74-4ea6-8877-24458a4dd796)

**Comment by m-1-k-3** [comment]
> Default installation was OK:
> <snip>

So, EMBA runs on the newest Kali ... thats great to hear. Thank you for supporting the testing tasks

**Comment by torabi12** [comment]
Will do the remaining 2 tests on tomorrow....

**Comment by m-1-k-3** [comment]
For my early adopters out there. Docker base image v1.4.2b (embeddedanalyzer/emba:1.4.2b) should be up in around 30mins.
This image is based on the new Kali and includes the new version of Capa and cwe_search

**Comment by torabi12** [comment]
This morning the installer used the 1.4.1f:

![kép](https://github.com/user-attachments/assets/bd10636f-d025-4412-8318-133ac9c13c62)

May I wait for the new one or should I use the actual environment for testing?

**Comment by torabi12** [comment]
My problem would be how to replace the 1.4.1f to the latest one manually to get emba use the new container. :(

**Comment by m-1-k-3** [comment]
For testing the updated base image the draft branch with some cleanup and refactoring can be used here #1302

**Comment by torabi12** [comment]
I remain on the master for the last 2 tests. I do not want to mix up the things. Thank you.
