### ISSUE TITLE
Support for Kali 2024.4

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#1301]
From the 2024.3 release notes [here](https://www.kali.org/blog/kali-linux-2024-3-release/):

_With Python 3.12, there will be a major change for users: it won’t be possible to install Python packages with pip anymore. [We wrote about that a year ago already](https://www.kali.org/blog/python-externally-managed/), we invite you to read that again if you are an avid user of pip._

_But that will be for the next Kali release, 2024.4, due by the end of the year._

As EMBA is heavily using pip, we need to check the possibilities and start testing as soon as Python 3.12 is landed.

**Comment by sagisar1** [comment]
I found a workaround, by using this command:
 rm /usr/lib/python3.12/EXTERNALLY-MANAGED
 
 it worked for me, as I don't use virtual environment and prefer using normal pip

**Comment by m-1-k-3** [comment]
as we are currently on a good way to keep everything up with the current dev release, we can close this and will work with dedicated issues if needed
