### ISSUE TITLE
How to reduce sbom detection time

### ISSUE THREAD

**Issue by chenjianquan7** [e-m-b-a/emba#1311]
**Is your feature request related to a problem? Please describe.**
How to reduce sbom detection time
I just want to perform sbom detection and output sbom files, but its detection time is very long, especially for S09_firmware_mase-version_check, which takes a lot of time. Do I have any other ways to improve efficiency? Thank you

![image](https://github.com/user-attachments/assets/ecaaff83-19cf-42ea-b0da-c080840f79a7)

**Comment by m-1-k-3** [comment]
If you are already using the sbom scan profile you could add the following to your profile `export QUICK_SCAN=1`. With this option only identifiers with known vulnerabilities are tested.
More CPU power is also a good solution for boosting up S09 :)

**Comment by m-1-k-3** [comment]
please also check #1323
