### ISSUE TITLE
documentation about scan profiles

### ISSUE THREAD

**Issue by qequ** [e-m-b-a/emba#1338]
**Is your feature request related to a problem? Please describe.**
hi, currently I'm using emba as default with no profiles but I've seen that there are already defined several profiles in `scan-profiles` but with no documentation about what options are set or skipped in each profile.

**Describe the solution you'd like**
wiki entries for the current scan profiles and what they do. Also a tutorial on how to make a custom scan profie  

**Describe alternatives you've considered**

**Priority issue**
Are you already a [Sponsor]? - N

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
If you check the default profile I think most of the options are explained or self-explaining:
https://github.com/e-m-b-a/emba/blob/master/scan-profiles/default-scan.emba

If something is unclear, please bring the option up and we can add a note.

**Comment by qequ** [comment]
when running without the scan profile flag (-p) does emba use implicitly a scan profile? the default one?

**Comment by m-1-k-3** [comment]
No, without a profile EMBA runs unconfigured and you need to configure it via parameters. At least you probably would use '-t' and '-W'. '-h' gives you more details on the possible parameters.

**Comment by qequ** [comment]
if i set env variables without using a profile will that work ? like
```
$ export MODULE_BLACKLIST+=( "S10_binaries_basic_check" "S110_yara_check" "S12_binary_protection" "S13_weak_func_check" "S14_weak_func_radare_check" "S15_radare_decompile_checks" "S16_ghidra_decompile_checks" "S17_cwe_checker" "S99_grepit" )

$ sudo ./emba -f path/to/firmware  -l path/to/logs -t 
``` 

will the blacklist work ?

**Comment by m-1-k-3** [comment]
No, currently we do not support environment variabls. The current approach is to use profiles or (where possible) command line parameters. I recommend to work with a scan-profile that you can adjust as you like

**Comment by m-1-k-3** [comment]
Looks as nobody is working on it. I will close this for now. Please re-open it if needed
