### ISSUE TITLE
Online check support repo returning empty hash values

### ISSUE THREAD

**Issue by secsonthebeach** [e-m-b-a/emba#1348]
It appears an automated commit to  ‘onlinecheck’ support repo removed hash values from some files about 5 days ago.
On my end this is causing an “IndexError: list index out of range” error when attempting `run-server.sh` for Embark.

**Comment by m-1-k-3** [comment]
Interesting ... I need to check on this.

**Comment by secsonthebeach** [comment]
It appears to have been commit 0f823f211a92b326eb6aa703a4bbbec01163bfed 
Each of the files updated 5 days ago are now blank. 

https://github.com/EMBA-support-repos/onlinecheck/commit/0f823f211a92b326eb6aa703a4bbbec01163bfed

**Comment by m-1-k-3** [comment]
should be fixed here https://github.com/EMBA-support-repos/onlinecheck/commit/c19e3fc57001b5434d0df18e2ba81802feed6962

**Comment by m-1-k-3** [comment]
Thank you for reporting. Please check it and reopen if needed

**Comment by secsonthebeach** [comment]
That did the trick. Thank you!

**Comment by m-1-k-3** [comment]
perfect
