### ISSUE TITLE
SBOM_error

### ISSUE THREAD

**Issue by nemanjastojan** [e-m-b-a/emba#1390]
![embasbom](https://github.com/user-attachments/assets/69d9abf7-b181-4590-8f29-cacf1d6b533a)

After basic command for analyzing my firmware __sudo ./emba -f path to my firmware/firmware name_ there's error in building just like on picture. This SBOM depedency tree builder goes with infinite dots. For example, default scan works fine for this firmware with this mistake. 

Also, complete scan works for some other firmwares?

**Comment by m-1-k-3** [comment]
We need further details for reproducing.

**Comment by nemanjastojan** [comment]
I'm sorry but I can't provide more details due to fact of confidentiallity. This issue can be deleted.
