### ISSUE TITLE
manual updater cve_searchsploit: not found

### ISSUE THREAD

**Issue by muddydev** [e-m-b-a/emba#182]
Not totally sure if it's an issue but didn't look right? 

```
└──╼ $sudo ./config/emba_updater
[sudo] password for ovarroadmin:
[*] EMBA update - cve_searchsploit update
./config/emba_updater: 9: cve_searchsploit: not found
[*] EMBA update - cve-search update
```

**Comment by m-1-k-3** [comment]
Indeed that does not look right ... I will take a look.

Thanks for reporting

**Comment by m-1-k-3** [comment]
@muddydev I have found the issue. On default installation there is no cve_searchsploit installation on the host and so this update fails. I will fix it in my next PR.

**Comment by m-1-k-3** [comment]
should be fixed now. Thanks for reporting
