### ISSUE TITLE
Typical cve-search issues

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#187]
### Local network issues

With the latest updates (see https://github.com/e-m-b-a/emba/pull/183) we have isolated the EMBA container from a networking perspective. This means EMBA is not able to reach the internet anymore. With this also some adjustments in the EMBA docker container and in the local mongodb configuration were needed.

The easiest way to get an updated EMBA installation are the following steps:
```
cd emba-directory
git pull
sudo docker pull embeddedanalyzer/emba
sudo ./installer.sh -d
```

If you are running into issues that the EMBA container is not able to access your mongodb installation you can check the following:

* The command ```ifconfig``` should show a new network interface with the following ip address:
```
└─$ ifconfig emba_runs
emba_runs: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.36.0.1  netmask 255.255.0.0  broadcast 172.36.255.255
        ether 02:42:cb:c9:37:80  txqueuelen 0  (Ethernet)
        RX packets 15643  bytes 964808 (942.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 43695  bytes 1435782652 (1.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
If this is not the case you can try to restart docker at all with the following command
`└─$ sudo /etc/init.d/docker restart  
`
Another way is to delete the network interface and re-initialize it:
```
└─$ sudo docker network rm emba_runs
└─$ sudo docker-compose up --no-start
```

* Your mongod.conf should have the following bindIp configuration:

```
└─$ grep bindIp /etc/mongod.conf
  bindIp: 172.36.0.1
```

### Mongod is not starting up

EMBA is complaining that CVE search works not as expected. Checking if mongod is listening, does not return an open port:

```
└─$ sudo netstat -anpt | grep 27017 
```

Also a restart of mongod does not help!

Please check if your harddisk was running out of space (e.g. with df -h). If it is full, clean it up and retry it.

### No results from CVE-search

Probably you are running into the issue that your network environment is working as expected and mongod is also listening on port 27017. If you are trying to query your CVE database you get no results:

![image](https://user-images.githubusercontent.com/497520/169757238-cff8ee06-5f8f-4894-bdbd-4bf8d076dfa6.png)

Sometimes it happens that the CVE database is corrupt. So, please do a full reinitialization and update the following way:

```
└─$ ./external/cve-search/sbin/db_updater.py -f
```

### Errors during database update

During a manual CVE database update you are running into the following errors:

![image](https://user-images.githubusercontent.com/497520/169758210-2ae3fda1-4c04-43fb-9542-9a9e58dff482.png)

It looks like [this](https://github.com/cve-search/cve-search/issues/636) or [this](https://github.com/cve-search/cve-search/issues/626) issue.

### Testing CVE-search manually

* Finally you can test it manually via starting the EMBA container and test the cve-search connection the following way:
```
└─$ sudo docker-compose run emba     
WARNING: The FIRMWARE variable is not set. Defaulting to a blank string.
WARNING: The LOG variable is not set. Defaulting to a blank string.
WARNING: The EMBA variable is not set. Defaulting to a blank string.
Creating emba_forked_emba_run ... done
┌──(root@d2a5960b73b2)-[/emba]
└─# /external/cve-search/bin/search.py -p busybox
```
This should show some CVE details regarding busybox.

**Comment by Hellworold** [comment]
Hi,
When iam trying to run the utility it gives an error CVE- search not working , check issue number 187 thus iam here .
Now i have checked all the steps above.
for some reason this is the output 
i have checked with some older versions 


![Screenshot_2022-09-29_16-37-35](https://user-images.githubusercontent.com/114690200/193138310-7a3f6a24-5d89-4725-9787-0430297ad8ae.png)

**Comment by Ret2c7** [comment]
Hi,
When iam trying to excute ./external/cve-search/sbin/db_updater.py -f，error have occurred。
![image](https://user-images.githubusercontent.com/59363523/236611204-461df3ff-dcd1-4b2e-8a2e-22c46b00bb6f.png)

**Comment by m-1-k-3** [comment]
Please check the following:

* is your network ok? -> ifconfig should show the `emba_runs` network device with ip address `172.36.0.1`
* is mongod running? `netstat -anpt | grep 27017`
* is redis running? `netstat -anpt | grep 6379`

**Comment by Ret2c7** [comment]
it seems like mongod didn't running 
![image](https://user-images.githubusercontent.com/59363523/236617227-5bc92b1a-1bb9-4cfd-a487-ce8df5ae42cf.png)
![image](https://user-images.githubusercontent.com/59363523/236617260-778b0fbc-a281-42e2-9a48-1eb37ec93114.png)
![image](https://user-images.githubusercontent.com/59363523/236617280-429d64ad-b492-49d4-8e63-f6c29eae9593.png)
![image](https://user-images.githubusercontent.com/59363523/236617359-d2e251f6-f652-4f9a-be6d-58137dfb6b41.png)

**Comment by m-1-k-3** [comment]
Then check mongod, restart it, check logs and as it is running you can do an update of the database.

**Comment by Darren-zl** [comment]
I follow the above operations to do, are normal. But I still show cve-search -no ok. I don't know why.
![image](https://github.com/e-m-b-a/emba/assets/53506045/6d78f495-5464-40a3-b361-812a8d34c137)
![image](https://github.com/e-m-b-a/emba/assets/53506045/a78210e5-3bd2-46b8-a4d0-062a7f4a4153)
![image](https://github.com/e-m-b-a/emba/assets/53506045/5ebc9470-4451-4aa7-8b69-aa4b00a989a7)
![image](https://github.com/e-m-b-a/emba/assets/53506045/947ebb0b-d9d2-4e7f-9719-2b39732c11ed)

**Comment by Ret2c7** [comment]
try again after ./external/cve-search/sbin/db_updater.py -f

**Comment by brainsht** [comment]
Found another source of cve-serach issues. Kept getting this error message while running ./external/cve-search/sbin/db_updater.py -f

`CVEDownloads - ERROR - Did not receive last-modified header in the response; setting to default (01-01-1970) and force update! Headers received: {'content-length': '93', 'cache-control': 'no-cache', 'content-type': 'text/html', 'connection': 'close'}`

@Ret2c7 try this one. Error is gone by adjusting max_workers to 1 in https://github.com/cve-search/cve-search/blob/1f0b50aa46814e2a683a9b7b01da8bcc0403154e/lib/DownloadHandler.py#L121

Afterwards ` ./external/cve-search/sbin/db_updater.py -f` works fine (takes longer though) and no cve-serach issue anymore for me. 

Really seems like there is a rate limit with https://nvd.nist.gov/
Source: https://github.com/cve-search/cve-search/issues/890#issue-1245042453

**Comment by m-1-k-3** [comment]
@brainsht thank you for documenting this issue. I will include it into the main post.

**Comment by aserper** [comment]
In my experience, trying to install EMBA on a server with a lot of cores (I have it running on a 36 core aws machine right now) causes the same issues with updating and populating the CVE database.  A workaround that I found to that issue is to run the emba installer solely by utilizing two cores. While I didn't really look into why it helps, I assume that the large number of cores opens more threads which causes some DDOS protection mechanism on the remote server to kick in (again, just a guess). This can be done by running the installer program like so:
`sudo taskset -c 0,1 ./installer.sh -d` which will run the installation script using only two cores. I know that you can go into the files and change the code but I'm lazy ;)

**Comment by m-1-k-3** [comment]
With version 1.3.0 we switched to python environment. This results in the need of activating the python environment before doing cve-search tasks. 

On the host system it is possible to activate it the following way:
```
└─$ source ./external/emba_venv/bin/activate
```

In the docker container it is possible to activate it the following way:
```
└─$ source /external/emba_venv/bin/activate
```

**Comment by m-1-k-3** [comment]
It is now recommend to setup a NIST API key
See also https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

**Comment by brainstorm** [comment]
> 
> `thread_map(self.download_site, sites, desc="Downloading files", max_workers=1)`
> 
> 
> Really seems like there is a rate limit with https://nvd.nist.gov/ Source: [cve-search/cve-search#890 (comment)](https://github.com/cve-search/cve-search/issues/890#issue-1245042453)

That `max_workers` argument is now exposed as `$HOME/.cvexplore/.env` as `MAX_DOWNLOAD_WORKERS` and you can define it along with the `NVD_NIST_API_KEY` variable.

`sudo taskset -c 0,1 ./installer.sh -d` is not yet documented in the wiki and I suspect that there are still threading issues within EMBA, probably (see: https://github.com/e-m-b-a/emba/issues/908#issuecomment-1825000276).

**Comment by m-1-k-3** [comment]
If you are running into cve-search issues please test https://github.com/e-m-b-a/emba/pull/913
