### ISSUE TITLE
pip3 install requirements.txt

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#218]
**Describe the bug**
The emba installer when uses the
pip3 install -r requirements
command this error comes:
![image](https://user-images.githubusercontent.com/98665813/154025643-dc964441-d3ab-4c13-b254-3e65d96d141e.png)

**To Reproduce**
1. EMBA installation (default mode)
2. See error

**Expected behavior**
pip3 install should be working fine.

**Screenshots**
Added above.

**Desktop (please complete the following information):**
 - OS: [Kali Linux 2022.01, 2021.4 and 2021.3]
 I have tested 3 different Kali versions including the latest one and I got the same issue.

**Comment by m-1-k-3** [comment]
which module of the installer is this error from? IF20_cve_search?

**Comment by m-1-k-3** [comment]
Looks like broken deps. This should work:
```sudo python3 -m pip install -Iv crackmapexec==5.1.7.dev0```
I will include this into the next update.

**Comment by torabi12** [comment]
Thank you the fix command, It was working on Kali 2022.1 with no PROXY.

**Comment by m-1-k-3** [comment]
are you running out of disk space?
