### ISSUE TITLE
I05-emba_docker_image download with PROXY fails

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#219]
**Describe the bug**
In case of PROXY the default installation of emba stops at I05_emba_docker_image download:
![image](https://user-images.githubusercontent.com/98665813/154026344-0bb803c3-b7e2-40df-9c21-bbd8156cfd2d.png)

**To Reproduce**
1. Set PROXY settings
2. EMBA installation (/default mode)
3. See error

**Expected behavior**
The image download should be working fine.

**Screenshots**
Added above.

**Desktop (please complete the following information):**
 - OS: [Kali Linux 2022.01]

**Comment by m-1-k-3** [comment]
Currently the proxy installation is not supported. You can disable the STRICT mode from the installer via setting the variable "STRICT_MODE=1" to 0 in installer.sh

Please do a quick check if this helps.

**Comment by torabi12** [comment]
Thank you, with STRICT_MODE=0 the installer went through the docker image download.

Best regards,
torabi

**Comment by m-1-k-3** [comment]
Thanks for testing and feeback. Good to know for future references and tests.
