### ISSUE TITLE
I get a error when i run the install.sh script

### ISSUE THREAD

**Issue by clb-by** [e-m-b-a/emba#22]
the error is these
![image](https://user-images.githubusercontent.com/54340060/102510371-81c5f780-40c2-11eb-8dca-1fa5433652c3.png)

i install the emba successfully before, but this i can't install successful

my enviroment is ubuntu18.04

**Comment by clb-by** [comment]
ok! I have resolved！

**Comment by clb-by** [comment]
binutils don't have include the <limits.h> and <fcntl.h> successfully，i reimport <limits.h> and <fcntl.h> head files

**Comment by p4cx** [comment]
Thank you for your research. I will update the installer soon, with some improvements overall. There I will update the binutils version to  2.35.1 instead of 2.34. Maybe they fixed it themselves and imported the right files.

**Comment by clb-by** [comment]
Maybe！I think this tool is pretty good!
