### ISSUE TITLE
embeddedanalyzer/emba docker image ERROR INSTALLING

### ISSUE THREAD

**Issue by rodry7** [e-m-b-a/emba#256]
**Describe the bug**
Whenever I try to install the embeddedanalyzer/emba docker image it just gives me the error: failed to register layer: Error processing tar file(exit status 1): write /external/arachni/arachni-1.6.1.3-0.6.1.1/.system/usr/lib/ruby/2.7.0/rdoc/generator/template/darkfish/fonts/SourceCodePro-Regular.ttf: no space left on device
------------------------------------------------------------------------------------------------
Error detected - status code 1

**To Reproduce**
1. EMBA installation (default mode)
2. sudo ./installer.sh -d 

**Expected behavior**
It should install without any problem I don't know why am I getting this error

**Screenshots**
![image](https://user-images.githubusercontent.com/60978158/174136334-eb0f074a-6f90-4d36-b141-cc8367c96ed3.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022

**Comment by p4cx** [comment]
How much space do you have on your machine? Your error message tells us that there is "no space left on device". 
You can check it with `df` on Kali Linux.

We are suggesting to have at least over 25 GB of empty space on your machine, because the docker container alone should take about 15 GB and it is never a bad idea to have some reserves.

**Comment by rodry7** [comment]
I think I had 80GB on the kali VM
![image](https://user-images.githubusercontent.com/60978158/174403530-3e877b85-e299-4d95-9eff-160a4d0ae740.png)
![image](https://user-images.githubusercontent.com/60978158/174403625-25c38314-ee6e-4927-bfcb-e36f9fb02e08.png)

**Comment by p4cx** [comment]
Somethings wrong with your disk in your VM. If I divide 18964304/1024/1024, then it gives about 18GB (or just use `df -h`). I have no idea if this is the right way to calculate that, but I checked it on my machine, it comes quite near to the output of `df -h`, therefore we can say, that the error message is not misleading and you haven't enough space on your disk. Downloading and extracting the Container needs at least more than 18GB space. I hope you can resolve your disk size issues.

**Comment by m-1-k-3** [comment]
As far as I can see in the output of the df command you only have 18GB of disk space and around 3GB are free. This is not enough for EMBA. Please check the prerequisites here: https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites
