### ISSUE TITLE
I am having an issue with the update. I used the help of many articles to try and fix it but none of them worked. I uninstalled and reinstalled kali but i am having the same error. 

### ISSUE THREAD

**Issue by AnikateSawhney** [e-m-b-a/emba#263]
I am using Kali 2022.2 at the moment. The error is with the update feature. 
![kali curse](https://user-images.githubusercontent.com/66863414/177054879-8d94dcf7-ed4a-4968-9a6d-835ddf029bc5.png).
I tried some of the solutions like changing http to https in the /etc/apt/sources.list file but it didn't work.
I tried doing the update with proxy and got the below error.
![proxychains](https://user-images.githubusercontent.com/66863414/177054930-ccfd6454-c10b-48f4-b180-ba069b268226.png)
My sources.list file is like this:-
![sources list](https://user-images.githubusercontent.com/66863414/177054990-7d09f51a-5d00-4cf0-9de7-45576927b2c8.png)

**Comment by m-1-k-3** [comment]
Hi,

 I did not get the issue completely. You are trying to install and update Kali Linux? What is the reason to use proxychains? Are you behind a proxy? Are you able to reach the Internet with your Kali?
