### ISSUE TITLE
dbus-launch error

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#284]
**Describe the bug**
There is an error when I start EMBArk:
![kép](https://user-images.githubusercontent.com/98665813/182344766-52f8fb57-9cd4-4216-8747-24d27adf925c.png)

**To Reproduce**
1. EMBArk installation (default mode)
2. Start EMBArk with the following parameters: sudo ./run-server.sh
3. See error

**Expected behavior**
Child process should be available.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04 LTS Desktop]

**Comment by m-1-k-3** [comment]
Is this EMBA or EMBArk related? Can you trigger this error also in EMBA or only in an EMBArk test?

**Comment by torabi12** [comment]
I am testing EMBArk installation and I reported to Benedikt this error and he suggested to open a bug for EMBA to track it.

**Comment by torabi12** [comment]
Hello All,

I installed only EMBA and I did a short test today and I got similar errors like above:

![kép](https://user-images.githubusercontent.com/98665813/182567860-192e1c77-65e8-4b97-9ca3-6941b4f3a880.png)

![kép](https://user-images.githubusercontent.com/98665813/182567878-9a2bcd5e-9d92-4232-aa07-3a80cde8e07d.png)

Ubuntu Desktop 22.04 LTS
git clone https://github.com/e-m-b-a/emba.git

Regards,
Torabi

**Comment by m-1-k-3** [comment]
Not sure if this is the new notification system. Could you try setting the following option to 1: https://github.com/e-m-b-a/emba/blob/a2986346274258588a735bd8e4673cb63a9217a5/emba.sh#L310

**Comment by torabi12** [comment]
I changed the 0 to 1 and the error didn't come.

**Comment by m-1-k-3** [comment]
Ok, looks like some Ubuntu special issue. Are the following commands available/installed? 
* inotifywait
* notify-send

Are you working in a graphical environment?

**Comment by torabi12** [comment]
Both are available on Ubuntu 22.04 LTS. I am using GUI and default installation.

**Comment by m-1-k-3** [comment]
ok, thanks for reporting. I will do some further testing.

**Comment by m-1-k-3** [comment]
Could you check if the following packages are installed:
* dbus
* dbus-x11

Should work with a command like the following:
`dpkg -l | grep dbus`
If these are not installed please install it and try again.

**Comment by m-1-k-3** [comment]
ok, I will setup a Ubuntu and take a look. Thanks for testing

**Comment by m-1-k-3** [comment]
just as a quick note ... if you are usually using the default profile, you can use the default profile without notifications enabled (https://github.com/e-m-b-a/emba/blob/master/scan-profiles/default-scan-no-notify.emba)

**Comment by jgamblin** [comment]
Just as an FYI, I am getting the same error using EMBA.

![Screen Shot 2022-08-04 at 8 06 26 PM](https://user-images.githubusercontent.com/8428124/182980242-3726ebc1-b0d1-462c-964f-3fad62ff965f.png)

**Comment by m-1-k-3** [comment]
Thank you @jgamblin for reporting this. As a quick workaround you can use the profile "./scan-profiles/default-scan-no-notify.emba" in the following way:

```
└─$ sudo ./emba.sh -f ~/firmware.bin -l ~/emba_logs -p ./scan-profiles/default-scan-no-notify.emba 
```

You can also disable this feature by setting the following option to 1:
https://github.com/e-m-b-a/emba/blob/76cdefad70d805aefa40c6f0552461c85e4bb7a6/emba.sh#L310

I will do some further tests soon and I am sure we can find and fix the issue.

**Comment by m-1-k-3** [comment]
Please try installing the package "notification-daemon":

```
sudo apt-get install notification-daemon
```
If it is then working you are fine. If not you need to create the following file:

```
/usr/share/dbus-1/services/org.freedesktop.Notifications.service
```
and add the following content:

```
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/lib/notification-daemon/notification-daemon
```

Please respond with your exact steps that helped in this thread. Thank you

**Comment by torabi12** [comment]
1st I just installed the notification-daemon:

![kép](https://user-images.githubusercontent.com/98665813/183118251-f549a739-f75f-4816-a225-cbcf2fc32e66.png)

it did not solve the issue:
![kép](https://user-images.githubusercontent.com/98665813/183118303-17b8b6ad-ce5a-4642-8515-7a0c5fb1fcca.png)

the I created the file with the content, but the error appeared again in the terminal more times:
![kép](https://user-images.githubusercontent.com/98665813/183118419-62e6ffd7-b1ff-4e22-84c8-5dec8021cb2e.png)

This is the file I added:

![kép](https://user-images.githubusercontent.com/98665813/183118513-f8d1668f-aee0-455f-8dd6-1ca1a9822214.png)

**Comment by jgamblin** [comment]
I am seeing the same behavior.

**Comment by m-1-k-3** [comment]
hmmm ... checked my history and found the following stuff I did:

```
apt-get install dbus dbus-x11
apt-get install libnotify-cil-dev
apt-get install notification-daemon
```
And then modified the mentioned file. Was it the package `libnotify-cil-dev` that I missed? Could you check this?

**Comment by torabi12** [comment]
I installed dbus-x11 and libnotify-cil-dev also but I got the error again:
![kép](https://user-images.githubusercontent.com/98665813/183134819-2a4644ed-295e-42a9-8144-50cc030351c9.png)

I had the same output when libnotify package was not installed but I tried with it also.

I usualy set back to a clean snapshot the VM to have a perfect test environment. The error only disappeared when I set the 0 to 1 in emba.sh in line 310, or somewhere there:)

**Comment by m-1-k-3** [comment]
Probably we should set it default to 0. On the other hand we need to solve this issue. Will give it a next try tomorrow

**Comment by m-1-k-3** [comment]
Please check #286

**Comment by p4cx** [comment]
This issue should now be resolved and notifications should work in Ubuntu. Just run `installer.sh -d` and then it should be good to go. If there are other problems in this direction, please reopen this issue or create a new one.

**Comment by torabi12** [comment]
OS: Ubuntu 22.04.1 LTS
emba installation was fine I didn't have any errors during the process.

I executed a short scan:
$ sudo ./emba.sh -f ../WRT54GS_3.17.4_US_code.bin -l /home/arpadb/WRT54GS -p ./scan-profiles/full-scan.emba

I got this error or similar error messages many times:
![kép](https://user-images.githubusercontent.com/98665813/184700275-2773169c-eee2-484d-9a6c-9ebfcdb3e05c.png)

![kép](https://user-images.githubusercontent.com/98665813/184700366-e2176f07-13dc-4ea9-919f-9298390c3383.png)

![kép](https://user-images.githubusercontent.com/98665813/184700482-a20532e5-95d3-4751-bbcc-f1ee86e7e454.png)

![kép](https://user-images.githubusercontent.com/98665813/184700572-50e702c8-2681-4bad-8acc-d7337fe1494f.png)

There were some other strange lines in the output where emba displayed a usage of the actual tool:
![kép](https://user-images.githubusercontent.com/98665813/184701321-2f68d674-aeab-453d-a4be-91e7fc0acfa9.png)

Please execute a similar scan for an older Linksys file if you would like to verify the above messages.
https://cyberforat.squat.net/openwrt/binary_images/linksys_official/WRT54GS_3.17.4_US_code.zip

**Comment by m-1-k-3** [comment]
The openssl error is occuring during the user-mode emulation. This is an expected message as the emulator enumerates through different parameters like -h, -v, -V, --help and so on.

**Comment by m-1-k-3** [comment]
The other issue looks like a known Ubuntu issue: https://www.google.com/search?q=gdbus+notifications+exceeded+maximum+number+of+notifications&rlz=1C1GCEB_enDE995DE995&oq=gdbus+notifications+exceeded+maximum+number+of+notifications&aqs=chrome..69i57.15575j0j7&sourceid=chrome&ie=UTF-8

**Comment by torabi12** [comment]
Thank you, for me it is OK, I just wanted to share with you to see if its emba related or not.
