### ISSUE TITLE
Scan Wont Finish On Ubuntu

### ISSUE THREAD

**Issue by jgamblin** [e-m-b-a/emba#287]
**Describe the bug**
Attempting to run a scan I am stuck on S115 for last 4+ hours with a alternating screen of `CVE-Search - Ok` and `CVE-Search - Testing`

**To Reproduce**
1. EMBA installation: **Default**
2. Use the firmware available here: https://static.tp-link.com/2018/201803/20180327/TL-WR902AC(US)_V3_171229.zip
3. Start EMBA with the following parameters: sudo ./emba.sh -l ./log -f ./firmware/TL-WR902AC(US)_V3_171229.zip -W
5. See error

**Expected behavior**
The scan to finish. 

**Screenshots**
![Screen Shot 2022-08-05 at 1 00 52 PM](https://user-images.githubusercontent.com/8428124/183134604-6d6458fb-3676-4a82-a1ac-b5bf224204b5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 - [Have been helping try to troubleshoot issue 284](https://github.com/e-m-b-a/emba/issues/284)

**Comment by torabi12** [comment]
Hello Jerry,

May I ask you the HW resources of your test machine?
I suppose that is a VM running in Virtual box or VMware, but what about the size of vRAM? vCPUs?

I have executed  alot of scans with EMBA or with EMBArk and I use 26GB RAM and 8 CPUs for the VM. The scan can be very very long, sometimes it can reach up to 2 days.

**Comment by m-1-k-3** [comment]
I will run a testscan of the firmware ... we will see

**Comment by jgamblin** [comment]
@torabi12 8 Cores and 16480MB of Memory.  How long a scan would take would be good information for the WiKi.  I was not expecting it to take days, but it makes sense. 

![Untitled](https://user-images.githubusercontent.com/8428124/183138418-6bd7ceee-4307-477c-98b7-9de756134699.jpg)

**Comment by torabi12** [comment]
I also tried to scan this FW, I extracted the ZIP and I only gave the BIN file to EMBA but it did nto start:
![kép](https://user-images.githubusercontent.com/98665813/183139658-e9d70b65-2cfa-415a-9866-c09945f76b6b.png)

I used this command for scan:
$ sudo ./emba.sh -f ../TL-WR902ACv3.bin -f /home/arpadb/TL-WR902ACv3_2 -W

I don't know what should be not OK now:(

**Comment by m-1-k-3** [comment]
My VM with 20 Gigs of RAM and 8 Cores (currently testing on my Kali) is now running less than an hour and already finished s115 (the emulator) and s116 (the version detection of the emulation results). I have started it with the default profile:

```
sudo ./emba.sh -f /home/m1k3/firmware_stuff/Firmware_images/TL-WR902AC(US)_V3_171229.zip -l /home/m1k3/firmware_stuff/emba_logs_tl-wr902ac -S -p ./scan-profiles/default-scan-emulation.emba
```
I will keep you updated ...

**Comment by torabi12** [comment]
binwalk is not installed by default on Ubuntu 22.04 LTS. After installing it I was able to start the scan for the bin file also.

**Comment by m-1-k-3** [comment]
you do not need to install binwalk on your host. All these deps should be installed in the docker container.

**Comment by m-1-k-3** [comment]
@jgamblin your test is running without threading. This will take a while. Could you try restarting your test with `-t` option or (in my opinion the best solution) start it with `-p scan-profiles/default-scan.emba`. If this works find you could also try to run the profile `scan-profiles/default-scan-emulation.emba`

The default profile sets some further options like: `-t -s -z -E -W`
The default profile with emulation enabled sets additionally the option `-Q`

**Comment by jgamblin** [comment]
I started it with the profile, and it just started to scroll this: 
![Screen Shot 2022-08-05 at 3 44 30 PM](https://user-images.githubusercontent.com/8428124/183160007-70870c02-e5ad-40b9-9d97-6050d9c389b6.png)

I am running it with just `-t` to see if I can get one complete run.

**Comment by m-1-k-3** [comment]
hell yea ... it works :) same here! This is the user-mode emulator (s115 module):

![image](https://user-images.githubusercontent.com/497520/183160512-8c996792-4263-4f6e-8563-0fa17d52419a.png)

Give it a bit of time. In my environment it is nearly finished:
```
[!] Pre-checking phase ended on Fri Aug  5 20:24:51 CEST 2022 and took about 00:00:57 
[!] Testing phase ended on Fri Aug  5 21:12:41 CEST 2022 and took about 00:48:47 
[!] System emulation phase ended on Fri Aug  5 22:49:03 CEST 2022 and took about 02:25:09 
```

![image](https://user-images.githubusercontent.com/497520/183160705-eb1bea2e-ac5b-426c-99ef-e969fa82c968.png)

**Comment by torabi12** [comment]
Good evening / afternon,

My test ended just now with these results:
![kép](https://user-images.githubusercontent.com/98665813/183202260-55a73935-4114-4f3d-8d85-191571d38f1d.png)

This was my init command:
$ sudo ./emba.sh -f ../TL-WR902ACv3_US_0.9.1_0.2.bin -l /home/arpadb/TL-WR902ACv3 -S -p ./scan-profiles/default-scan-emulation.emba 

I don't like to feed emba with zip and other files, I just add the main FW file to have clean scan.

Regards,
torabi

**Comment by m-1-k-3** [comment]
Looks good ... Test ended. Then there is the error from the notification environment on Ubuntu. Go to the log directory and there should be all the results.

**Comment by m-1-k-3** [comment]
Please check #286

**Comment by jgamblin** [comment]
Thank You!  I was finally able to complete a firmware scan this afternoon. 

![Screen Shot 2022-08-06 at 3 42 56 PM](https://user-images.githubusercontent.com/8428124/183265439-180664c4-76e3-4802-8879-2732be952752.png)

**Comment by m-1-k-3** [comment]
I think it is solved for now. I will note that we need to improve our docs. New users should find the right way easier.

Thanks for pointing me on this issue. Will close this issue for now.
