### ISSUE TITLE
Kali Linux 2022.3 released

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#289]
**Is your feature request related to a problem? Please describe.**

Kali Linux 2022.3 released here: https://www.kali.org/blog/kali-linux-2022-3-release/
We need to test EMBA on it

**Testcases:**

- [x] Default/docker installation working (./installer.sh -d)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
- [x] Full installation working (./installer.sh -F)
  - [x] EMBA run in dev mode with options -s -z -S -D -E -t -W -Q
  - [ ] EMBA run in dev mode with options -s -z -S -D, -c, -E, -t, -W -Q -> **FAILED -  see https://github.com/e-m-b-a/emba/issues/290**
- [x] Docker build (./installer.sh -D)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)

**Comment by torabi12** [comment]
I did a default installation on Kali 2022.3 with emba and I didn't get any errors. I also checked this scan:
$ sudo ./emba.sh -f ../WRT54GS_3.17.4_US_code.bin -l /home/kali/WRT54GS -p ./scan-profiles/full-scan.emba

and I got the final report without problems:
![kép](https://user-images.githubusercontent.com/98665813/185738888-c570950b-a1ba-46b9-a6be-fd2335489451.png)

**Comment by m-1-k-3** [comment]
The current cwe-checker installation is broken. I will open a dedicated issue for this

**Comment by m-1-k-3** [comment]
EMBA is running quite smooth on the newest Kali Linux v2022.03. The cwe-checker installation will be handled in a separate issue. An updated docker container will be created and published soon
