### ISSUE TITLE
Many links on html-report index.html contain original filename extensions causing 404 errors

### ISSUE THREAD

**Issue by n0x08** [e-m-b-a/emba#297]
**Describe the bug**
The index.html page of web reports has many instances where the page links are things like:

file.txt.html
file.csv.html
file.html.html

These cause 404 when clicked & require manually removing the additional file extension from the URL.

**To Reproduce**
1. EMBA installation (using version updated 8/31/2022)
2. Run EMBA with -W flag
3. Copy html-report directory structure to web server root folder
4. Attempt to browse links on index.html page
5. Receive 404 errors for many pages

**Expected behavior**
Links on index.html page should accurately reflect sub-pages in the report directory

**Screenshots**
![image](https://user-images.githubusercontent.com/34355466/187806403-12304c9f-e55f-4e78-a180-32d261c49c02.png)
![image](https://user-images.githubusercontent.com/34355466/187806918-36237266-8a0d-44af-ae56-3e56d47d21d2.png)

**Desktop (please complete the following information):**
Linux emba 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by dgutson** [comment]
Tag @qequ

**Comment by p4cx** [comment]
Thank you for reporting this issue. I'll take a look at that soon!

**Comment by m-1-k-3** [comment]
@dgutson I did a grep on index.html but I have not found the orig. filename with the .txt in it:

![image](https://user-images.githubusercontent.com/497520/188125419-4922831e-7eb1-4375-a8a6-3323b2c3089c.png)

Could you provide further details how to get these results?

**Comment by dgutson** [comment]
@m-1-k-3 actually the OP was @n0x08  :) That goes to him.

**Comment by n0x08** [comment]
I ran emba with this command: sudo ./emba.sh -W -l ./firmware.log -f ~/firmware.dav -p scan-profiles/default-scan-emulation.emba

And when I check the index.html I see the .txt.html and .html.html links

![image](https://user-images.githubusercontent.com/34355466/188175674-9953ee0c-4624-4a3b-a7b2-52de37a4cd62.png)
![image](https://user-images.githubusercontent.com/34355466/188175799-aa46acfe-b794-4d17-9688-0567b55b2345.png)

**Comment by m-1-k-3** [comment]
Ha ... got it! Something with your command line is causing this issue.

As a quick work a round could you please try to call EMBA the following way:
```
sudo ./emba.sh -f ~/firmware.dav -l ~/firmware_log -p ./scan-profiles/default-scan.emba 
```
* The -W parameter is already set in the profile
* firmware.log -> please remove the "."
* Please store the logs outside of the emba directory

I need to verify what the actual issue is but with this command it should work and produce a correct report

**Comment by n0x08** [comment]
I still get the same behavior; I used this start command: nate@emba:~/emba$ sudo ./emba.sh -f ~firmware.dav -l ~/firmware.log -p scan-profiles/default-scan.emba

[+] EMBA start command: ./emba.sh -f /home/nate/firmware.dav -l /home/nate/firmware.log -p scan-profiles/default-scan.emba

I tested the same firmware image and the number of corrupted links changed; this is the count of the test run with your suggested syntax:

![image](https://user-images.githubusercontent.com/34355466/188217209-3a55bbee-e740-4a7a-8eb0-33fe61237cf5.png)

And this is the count from my initial report:
![image](https://user-images.githubusercontent.com/34355466/188217303-c9ed6289-2235-40b0-9708-8088376ef846.png)

**Comment by n0x08** [comment]
I get the same behavior when I omit .log from the logging directory. Same statistics on corrupted links as in my first screenshot above.

**Comment by m-1-k-3** [comment]
Are there any old logfiles in the emba directory e.g. from your initial tests? e.g., /home/nate/emba/firmware_log or /home/nate/emba/firmware.log

Could you please clean the emba dir (e.g., move them to a different place) and give it another try?
btw. you can also use the dots in your log directory and the double -W parameter also does not matter. Just remove it from the emba directory. If you can confirm this behavior I will improve our check on this case.

**Comment by dgutson** [comment]
@m-1-k-3 maybe it'll be easier if we try to solve this ourselves given that we have the input data to reproduce the issue.
@qequ could you please try to reproduce Nate's issue? If so, I propose to assign this to @qequ and let him fix it.

**Comment by n0x08** [comment]
I cleared out *all* log directories from the emba folder and the parent and now it doesn't corrupt the URLs. I had an unrelated log directory from a different firmware in my emba folder that I had forgot about. I was removing the log directories before each iteration of this testing so I guess it was the old one causing the issue. Thank you for the help!

**Comment by dgutson** [comment]
Just curious, question to maintainers: what's the relationship between logs/logs dir, and URLs corruption?

**Comment by m-1-k-3** [comment]
the question for next week ;)

**Comment by p4cx** [comment]
I figured it out. EMBA checks in the web report whether the modules really exist and found the old log files instead of the modules themselves and wrongly linked them. #300 should solve the problem.
