### ISSUE TITLE
WSL-docker-setup

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/emba#338]
Since there are different ways docker is integrated with the WSL there should be an option to skip the Docker-setup.
(docker.io etc., network is bridged in WSLv1 in WSLv2 its NATed etc.)
Currently EMBArk don't work properly inside WSL2-ubuntu with docker-desktop integration.

See here:[WSL2-doc](https://docs.docker.com/desktop/windows/wsl/#best-practices)

Related: [EMBArk-PR-Tracking](https://github.com/e-m-b-a/embark/pull/58)

**Comment by BenediktMKuehne** [comment]
"To avoid any potential conflicts with using WSL 2 on Docker Desktop, you must [uninstall any previous versions of Docker Engine](https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine) and CLI installed directly through Linux distributions before installing Docker Desktop." - [WSL2-doc](https://docs.docker.com/desktop/windows/wsl/#best-practices)

**Comment by m-1-k-3** [comment]
Are you talking about Docker Desktop and not about a plain Ubuntu/Kali with an installation of the docker service?

**Comment by BenediktMKuehne** [comment]
It's an issue when the Docker engine is running on the Windows host and WSL provides the docker backend.

![image](https://user-images.githubusercontent.com/62940240/194289030-e495a995-ddd2-42bc-bde0-9c37943071fc.png)

**Comment by m-1-k-3** [comment]
hmmm, currently we have only tested and supported the installation of docker within the wsl2 Ubuntu system. I have never tested it with Docker desktop.

See also here: https://github.com/e-m-b-a/emba/wiki/Experimental-WSL-support

Probably we need a different installation path for getting this up and running

**Comment by BenediktMKuehne** [comment]
Would require moving CVE-search inside EMBA container.

**Comment by m-1-k-3** [comment]
To make this happen we need to find a way to update cve search inside of the container easily
