### ISSUE TITLE
Installation fails on Kali WSL environment - Error detected - status code 1

### ISSUE THREAD

**Issue by rancho666** [e-m-b-a/emba#342]
**The error**
Error detected - status code 1
Command:  echo -e "Command:  $ORANGE$BASH_COMMAND$NC"
Location:  ./installer.sh, line 196
Stack Trace:
    [1] main(): ./installer.sh, line 196 -> main -d

Maybe the output of the docker compose doesn't like it?

**To Reproduce**
EMBA installation (default mode) > "sudo ./installer.sh -d"

**Screenshots**
![image](https://user-images.githubusercontent.com/45133851/195619331-e3c9f8b4-2f73-4664-8781-9c3f54dff96f.png)

![image](https://user-images.githubusercontent.com/45133851/195620287-5725375c-f1cf-487d-8857-537ce9407e04.png)

**Desktop (please complete the following information):**
 - OS: [Kali Linux 2022.03 on WSL W11]

**Comment by m-1-k-3** [comment]
Just as a quick note: WSL support is only very experimental. I'm not surprised it fails ;) 
Have you checked our wiki entry on this topic? https://github.com/e-m-b-a/emba/wiki/Experimental-WSL-support

**Comment by m-1-k-3** [comment]
I'm wondering on the output of your screenshot. in line 196 should be a command `docker-compose` but the shown error indicates it is `docker compose`

**Comment by m-1-k-3** [comment]
uh, I can see the problem. This is the output on my machine:
```
docker-compose version 1.29.2, build unknown
```
And so the check is failing. As quick workaround just comment the docker-compse check (line 196-202). I will fix this issue soon.

**Comment by rancho666** [comment]
Workaround successful. Thanks for your help/time :)

**Comment by m-1-k-3** [comment]
@rancho666 could you please check PR https://github.com/e-m-b-a/emba/pull/347
This should fix the issue
