### ISSUE TITLE
Uninstall breaks mongod.conf

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/emba#345]
**Describe the bug**
When using the remove option, EMBA removes conf file.
And the file can't get reinstalled.

**To Reproduce**
1. EMBA installation (dev-mode/default mode)
2. Try to remove and reinstall
3. See error

**Expected behavior**
Should rather rewrite default conf? idk

**Screenshots**
![image](https://user-images.githubusercontent.com/62940240/195827061-0c29ab59-faa8-45b6-aaab-4e731e366160.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu22

**Comment by m-1-k-3** [comment]
should be addressed with this PR https://github.com/e-m-b-a/emba/pull/346
