### ISSUE TITLE
Pause and resume functionality

### ISSUE THREAD

**Issue by a-huk** [e-m-b-a/emba#353]
This idea came as I was running a large firmware (4gb) analysis and it is taking relatively long (40 hours and counting) on relatively modern and powerful hardware. No issues there, but it would be nice if the analysis could be paused and resumed at a later date. I understand that some checks and modules can not be resumed in the middle of them, but simply restarting from the last completed module would be helpful. 

Thanks for the awesome project

**Comment by m-1-k-3** [comment]
You could try to stop the analysis via <Strg>+<C>. If you start the same firmware test again EMBA will give you a note that there is a test already available and not finished. EMBA will then try to resume this scan. This works most of the time not too bad but has currently some limitations:
* Web reporter looses links
* Live tester modules (-Q) are currently not supported to be resumed
* Probably a lot more limitations and bugs
* Warning: this feature is highly experimental!

**Comment by m-1-k-3** [comment]
Should look like the following screenshot:

![image](https://user-images.githubusercontent.com/497520/196453790-5fcd155c-7723-41a7-833e-36d6e749820e.png)

press "n" and EMBA will try to use as many results from the first scan as possible

**Comment by m-1-k-3** [comment]
Can we get an update on this issue?
