### ISSUE TITLE
EMBA return value

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/emba#372]
**Describe the bug**

**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh
3. Run any firmware
4. Error:
Report-dashboard empty

**Expected behavior**
Return 0 on success?

**Screenshots**
![vmware_GCupRqt8Hm](https://user-images.githubusercontent.com/62940240/198656434-b8c98bea-0e5c-47b8-8e48-a88ccb8b49fe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22XX

**Additional context**
0 expected-> Exception trown since it is not 0
2 options:
1.  Fix EMBA return code
2. Ignore code in EMBArk

**Comment by BenediktMKuehne** [comment]
EMBA-Version: 1.1.2
FW: DIR-300A1_FW105b09.bin
default-scan

**Comment by m-1-k-3** [comment]
wtf 
![image](https://user-images.githubusercontent.com/497520/198715259-aa78d9e6-c9cb-4435-8ae4-6d989476d71b.png)
