### ISSUE TITLE
Not able to re-run the system emulation using the files generated using EMBA

### ISSUE THREAD

**Issue by keeplearning-rgb** [e-m-b-a/emba#376]
System emulation is completed in case of EMBA.
But when i am re-running the emulation using the run.sh script provided. It gets stuck on qemu-system-{arch} cmd and doesn't move further.

![image](https://user-images.githubusercontent.com/72157228/199708393-14b54136-a4a0-4725-a790-337176a5d846.png)

Utilities required are already installed on the system

**Comment by m-1-k-3** [comment]
Have you checked your local directory for some qemu log file?

**Comment by keeplearning-rgb** [comment]
Checked the log files. Its working now was missing some utilities.
Thanks for the help. this issue can be closed
