### ISSUE TITLE
Analysis during system mode emulation

### ISSUE THREAD

**Issue by keeplearning-rgb** [e-m-b-a/emba#377]
During the system mode emulation are we covering the scanning part as mentioned in last point of system mode emulation wiki. OR we have to manually trigger these things

![image](https://user-images.githubusercontent.com/72157228/199905199-36f55491-89c4-4d86-9385-fe5d4e5410f0.png)

**Comment by m-1-k-3** [comment]
If you run it with -Q parameter or with the default-emulation or with full-scan profile AND we have services up and running it should run automatically.

**Comment by keeplearning-rgb** [comment]
Which services you are referring to here?

**Comment by m-1-k-3** [comment]
If we detect a service up and running in L10 further Lxx modules are automatically running. Does not matter which service. This should be indicated with the output of "[+] Network services are available."

**Comment by m-1-k-3** [comment]
![image](https://user-images.githubusercontent.com/497520/199921565-8c3759a0-b3b6-4d94-833b-0441ea51685f.png)

**Comment by keeplearning-rgb** [comment]
Understood. It works for me in one of the firmware where some services got up and running. 
Nmap scan was done for those.

Thank you. this issue can be closed
