### ISSUE TITLE
error no more space.... but plenty of diskspace available

### ISSUE THREAD

**Issue by rjgjansen** [e-m-b-a/emba#378]
following the installation instructions  https://github.com/e-m-b-a/emba
the installation fails 
![emba space](https://user-images.githubusercontent.com/112406986/199930008-939754f5-fcd2-4ef9-9968-404b816855f1.png)

there is available disk space
![embadisk](https://user-images.githubusercontent.com/112406986/199930297-28c522d5-1880-4751-8b93-6b7d49c8809b.png)

what am i doing wrong

**Comment by m-1-k-3** [comment]
The docker images needs around 12-13gigs and in a default installation the docker directory is on / which has only 8.6gigs. You can try to move your docker directory to another disk and make a sym link to it. Usually this directory is `/var/lib/docker`.

**Comment by rjgjansen** [comment]
HI,

tnx...  a fellow student claimed it was a memory problem....  i put an extra 8 gb of mem from an other computer and the problem was gone.  also the other error messages were gone.
________________________________
Van: Michael Messner ***@***.***>
Verzonden: vrijdag 4 november 2022 09:59
Aan: e-m-b-a/emba ***@***.***>
CC: Ruud-Jan Jansen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [e-m-b-a/emba] error no more space.... but plenty of diskspace available (Issue #378)


The docker images needs around 12-13gigs and in a default installation the docker directory is on / which has only 8.6gigs. You can try to move your docker directory to another disk and make a sym link to it. Usually this directory is /var/lib/docker.
