### ISSUE TITLE
Installation failed due to trickest-cve pull

### ISSUE THREAD

**Issue by jblu42** [e-m-b-a/emba#383]
**Describe the bug**
Installation of Emba in Ubuntu 22.04 fails with Error:
fatal: unable to access 'https://github.com/EMBA-support-repos/trickest-ĵcve.git/': The requested URL returned error: 400

in IF20_cve_search.sh Line 91 there is a strange character here:
git clone https://github.com/EMBA-support-repos/trickest-ĵcve.git external/trickest-cve

**Comment by jblu42** [comment]
Just checked, was introduced when updating the Repos to EMBA-support-repos:
https://github.com/e-m-b-a/emba/commit/6c96eee988cccfb7ac7a2d436d73946d25368d5e

**Comment by m-1-k-3** [comment]
Nasty typo ...
