### ISSUE TITLE
Possible to disable grepit module

### ISSUE THREAD

**Issue by jblu42** [e-m-b-a/emba#393]
Is is possible to disable the intelligent grepit module? I found no switch for this?

**Comment by m-1-k-3** [comment]
Could you check this https://github.com/e-m-b-a/emba/wiki/Tweak-your-scan

**Comment by m-1-k-3** [comment]
Is this solution working for you?

**Comment by jlucius** [comment]
I tested it and with the blacklist I can disable the grepit, so this essentially solves it. But the way I am using emba it would be great to customize an individual scan as much as possible. If I blacklist it, it will be disabled for all scans.

My suggestion would be to enhance the customizing of a scan by:
- Adding more variables for additional scan modules so it can be customized by scan profiles
- Better naming of variables, currently it is not clear which variables disable scan modules and which are for other options (e.g. name it S99GREPIT)
- Better convention how to disable a module by variable (sometimes a message is outputted, sometimes not)

Would that be a possible approach for you? I can also try to make a first draft if you agree to this approach

**Comment by m-1-k-3** [comment]
Perfect that it works this way.

If you would like to disable it via a grepit-disable-scan-profile you should be able to setup a dedicated blacklist with only the grepit module in it and load it in your profile with the following code (untested):
```
  if [[ -f "$CONFIG_DIR"/grepit_blacklist.txt ]]; then
    readarray -t MODULE_BLACKLIST < "$CONFIG_DIR"/module_blacklist.txt
  fi 
```
I think the loading of the profile is after the initial blacklist setup and you can just set the array new.

You should be also able to populate the array without a file quite easily in your profile, e.g., `MODULE_BLACKLIST=( "sxyz_module_bla" "sabc_another_module" )` -> also untested

Doing it with parameters can be done by just enabling the relevant modules the following way: `-m s09 -m s115`
This automatically enables the pre-checkers and the finishing modules and you can define which scanning module should work.
Probably an additional parameter for disabling just a dedicated module would be a usefull addon. In the background this could be also used to populate the MODULE_BLACKLIST array.

I would not recommend introducing further dedicated variables for enabling/disabling modules. The MODULE_BLACKLIST way should work and can be extended to fulfill the needs.
