### ISSUE TITLE
requests package question

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#405]
**Describe the bug**
During the emba test, the CVE search worked, but after a while the database became inaccessible and CVE-search stopped working.
I tried to follow #187 and I checked the installed requests version:

![kép](https://user-images.githubusercontent.com/98665813/202923110-3a424d68-ac7c-4695-840b-ab45c37a8d9f.png)

but emba uses an older one package:

![kép](https://user-images.githubusercontent.com/98665813/202923174-2c2cd028-915b-47c3-8ec3-8ad58d5aab47.png)

Under the scan when CVE-search was working I had this issue:
![kép](https://user-images.githubusercontent.com/98665813/202923244-b4776b40-61df-4ef7-980a-d2800b4713db.png)

maybe it is independent of the CVE problem, but I was not able to finish the scan.

docker-compose gave this message:
![kép](https://user-images.githubusercontent.com/98665813/202923390-cda83f34-5238-49b0-b46e-80edaa1c5377.png)

Can I ask for help to get emba to use the latest appropriate request package?

**To Reproduce**
1. EMBA installation (default mode)
2. Use the firmware available here: https://download.zyxel.com/XGS4600-32F/firmware/XGS4600-32F_4.70(ABBI.4)C0.zip
3. Start EMBA with the following parameters: sudo ./emba.sh -l ~/XGS4600-32F -f ~/470ABBI4C0.bin -p ./scan-profiles/default-scan.emba -X "4.70(ABBI4)C0" -Y "ZxYEL" -Z "XGS4600-32F" -N "470ABBI4C0.bin"

**Desktop (please complete the following information):**
- OS: Kali Linux 2022.03
- EMBA version: actual master branch
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
Looks like there are multiple issues:
* requests package not updated on your host. Could you please try the following: `sudo pip3 install -U requests`
* Some issue with stacs. I will do a test with your firmware.
* mongod not running results in the connection issues from cve-search and the updater. Please do a `sudo service mongod restart` and try again. Also check for open port 27017 via netstat or something similar

**Comment by m-1-k-3** [comment]
Should there be a root directory in the firmware? 
![image](https://user-images.githubusercontent.com/497520/203007557-8f85f5df-94a8-4152-bc0d-682e9de3b86d.png)

**Comment by torabi12** [comment]
Unfortunately I don't know, it's an unknown firmware, I just wanted to test it.
My scan was running for at least 1 hour or more and after that CVE-search went wrong and I stopped it.

I can look at the above tonight when I get home.

**Comment by torabi12** [comment]
I did a clean installation and I checked the lines during the emba setup, I found these regarding requests in this order:
![kép](https://user-images.githubusercontent.com/98665813/203121735-6ca4fafe-fa93-4ca5-a266-74ce7b536a3c.png)

![kép](https://user-images.githubusercontent.com/98665813/203121768-42c58310-a90c-417c-87b0-233791959c35.png)

and after the install I checked it:
![kép](https://user-images.githubusercontent.com/98665813/203121862-512b3f87-0f36-48c9-b567-b18d587a4cc3.png)

**Comment by m-1-k-3** [comment]
> I did a clean installation and I checked the lines during the emba setup, I found these regarding requests in this order

Thanks, thought we fixed this already. I will check this

**Comment by m-1-k-3** [comment]
I think you can fix this on your host with the following command:

```
sudo pip3 install --force-reinstall --no-deps --ignore-installed requests==2.28.1
```
I need to build a new docker image to get it also into the container environment.

**Comment by torabi12** [comment]
Thank you, the command was working fine!

**Comment by m-1-k-3** [comment]
The stacs issue is now also solved here https://github.com/stacscan/stacs/issues/30
I will build a new container the next week and we are good to go.
Thanks for reporting the issues.

**Comment by torabi12** [comment]
Great news, thank you!

**Comment by torabi12** [comment]
Can I request a message when the container is updated?

**Comment by m-1-k-3** [comment]
Should be up

**Comment by torabi12** [comment]
After the emba install:
![kép](https://user-images.githubusercontent.com/98665813/204342158-5b6a1ab4-a75a-45de-b444-3896ed42fe10.png)

**Comment by m-1-k-3** [comment]
Looks good, doesn't it?

**Comment by torabi12** [comment]
Yes, it does:)
