### ISSUE TITLE
Kali Linux 2022.4 tests

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#426]
New Kali Linux is out: https://www.kali.org/blog/kali-linux-2022-4-release/
We need to test EMBA on it

**Testcases:**

- [x] Default/docker installation working with current docker image (`./installer.sh -d`)
  - [x] dependency check (`./emba.sh -d`)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)
- [x] Full installation working (`./installer.sh -F`)
  - [x] dependency check (`./emba.sh -d`)
  - [x] EMBA run in dev mode with options -s -z -S -D -E -t -W -Q
  - [x] EMBA run in dev mode with options -s -z -S -D, -c, -E, -t, -W -Q
- [x] Docker build (`sudo docker-compose build --no-cache --pull`)
  - [x] dependency check (`./emba.sh -d`)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)

**Comment by torabi12** [comment]
If I can take part I would do the first scenario, default docker install of EMBA and 2 tests on the latest Kali.

**Comment by m-1-k-3** [comment]
> If I can take part I would do the first scenario, default docker install of EMBA and 2 tests on the latest Kali.

For sure. Could you please use a "known good" firmware which is working with Kali 2022.3.

**Comment by torabi12** [comment]
I created a new Kali 2022.4 from the 7z, then
$ sudo apt update and upgrade and installer.sh -d

It dropped 2 times this:

![kép](https://user-images.githubusercontent.com/98665813/206866208-ffbaec92-5a9e-40d6-8c22-14fedac5743f.png)

and the CVE database download failed:

![kép](https://user-images.githubusercontent.com/98665813/206866223-3f1906bc-2245-4037-bda2-4abbd9e449c0.png)

![kép](https://user-images.githubusercontent.com/98665813/206866227-8b2a1cb1-f960-4f39-99f1-6237a992198e.png)

I have a snapshot of the clean system and I try again, but this is the fast experience.

**Comment by torabi12** [comment]
Installation dropped only the issue [#427](https://github.com/e-m-b-a/emba/issues/427) 2 times.

I used for testing the [DVRFv0.3](https://github.com/praetorian-inc/DVRF) binary file.

Starting command for 1st test was:
$ sudo ./emba.sh -l ~/DVRF -f ~/DVRF_v03.bin -p ./scan-profiles/default-scan.emba -S -X "v0.3" -Y "DVRF" -Z "Router" -N "DVRF_v03.bin" 

and at the end:
![kép](https://user-images.githubusercontent.com/98665813/206872625-9a3a6572-b20d-45ba-b9cd-02b75b3d41b7.png)

Report looks good and the scan was also OK.
If you have any suggestions on what I should pay more attention to, please let me know. The second test will be soon.

**Comment by torabi12** [comment]
So far I've run few emulation firmware tests and I only have one binary to run this with emba. I used [this]([http://www.downloads.netgear.com/files/GDC/WNAP320/WNAP320_V3.7.11.4.zip](https://www.downloads.netgear.com/files/GDC/WNAP320/WNAP320_V3.7.11.4.zip?_ga=2.129688654.316720904.1670755468-1077761920.1670755468))

Starting command:
$ sudo ./emba.sh -l ~/WNAP -f ~/WNAP320_V3.7.11.4.zip -p ./scan-profiles/default-scan-emulation.emba -S -X "V.3.7.11.4" -Y "Netgear" -Z "WNAP320" -N "WNAP_V3.7.11.4.zip" 

Ended like this:
![kép](https://user-images.githubusercontent.com/98665813/206900029-be1a5d18-a75e-41e0-9bcc-fbd1a7eea634.png)

I had only this at the beginning:
![kép](https://user-images.githubusercontent.com/98665813/206900066-9314c1b3-3834-4c7e-a518-68fc8534d5e3.png)

I added a not existing log folder into the command, I don't know why this question came up.

Report was also nice:
![kép](https://user-images.githubusercontent.com/98665813/206900169-9ffac651-91d7-48fa-8ee0-83ee4051aa35.png)

**Comment by m-1-k-3** [comment]
The logs directory in the EMBA root directory is probably from a EMBA run without the log parameter `-l`. If you start EMBA without a log directory it automatically generates the default one. I have seen that also `./emba.sh -d` creates such a log directory. So, this is a bug. Thank you.

**Comment by torabi12** [comment]
Yes I made a mistake, at the very beginning I entered the emba.sh command without -l -f parameters and after I executed the full command.

**Comment by torabi12** [comment]
I checked the full installation mode and it stopped at this point:

![kép](https://user-images.githubusercontent.com/98665813/206902402-4ce2ebb5-47c1-4981-9d5d-e552273035fd.png)

and got back the prompt.

**Comment by m-1-k-3** [comment]
could you please show me the output of the following command:

```
ls -ld /home/kali/emba/external/*
```

**Comment by torabi12** [comment]
The folder looks like this:
![kép](https://user-images.githubusercontent.com/98665813/206912170-8e27a28e-830f-44d4-8e1b-bfa4810f2048.png)

**Comment by m-1-k-3** [comment]
This looks correct. Currently I'm setting up another kali for further testing. First issues are already addressed with #429 and #428

**Comment by m-1-k-3** [comment]
> I tried the installation 2 times and I got the same:

Got it also. I will take a look at it

**Comment by torabi12** [comment]
I checked again the full installation recently and it stopped with the same error like above:

Stack Trace:
    [1] IP12_avm_freetz_ng_extract(): ./installer/IP12_avm_freetz_ng_extract.sh, line 86 -> IP12_avm_freetz_ng_extract
    [2] main(): ./installer.sh, line 259 -> main -F

**Comment by torabi12** [comment]
I tried again but the installer stopped the same place:

![kép](https://user-images.githubusercontent.com/98665813/207599989-3d18a702-feb5-490a-8016-63bb9c18bc92.png)

**Comment by m-1-k-3** [comment]
The full installation is not fixed yet. The docker image is used in default installation mode.

**Comment by torabi12** [comment]
The default installation has been working for me for the last few days, so I thought it was worth trying the full one.
I have just installed a default one but found no difference in the process.

The red lines were there:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyppeteer 1.0.1 requires pyee<9.0.0,>=8.1.0, but you have pyee 9.0.4 which is incompatible.                                                                                                                                                
ospd-openvas 22.4.0 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.                                                                                                                                     
ospd-openvas 22.4.0 requires paho-mqtt<2.0.0,>=1.6.0, but you have paho-mqtt 1.5.1 which is incompatible.

If you can help me with what to check, I'll try.

**Comment by m-1-k-3** [comment]
Is on the todo list

**Comment by m-1-k-3** [comment]
> I checked again the full installation recently and it stopped with the same error like above:
> 
> Stack Trace: [1] IP12_avm_freetz_ng_extract(): ./installer/IP12_avm_freetz_ng_extract.sh, line 86 -> IP12_avm_freetz_ng_extract [2] main(): ./installer.sh, line 259 -> main -F
> 
> ![kép](https://user-images.githubusercontent.com/98665813/207110274-e4715607-980a-4014-acd1-c59b7fa20c47.png)

addressed with https://github.com/e-m-b-a/emba/pull/433

**Comment by torabi12** [comment]
I tried the full installation and the process stopped like before:

![kép](https://user-images.githubusercontent.com/98665813/208111012-9d256530-3254-4866-9a58-2243452520f8.png)

I used a brand new Kali 2022.4 with
$ sudo ./installer.sh -F

I cloned the emba after the #433 merge to main.

**Comment by m-1-k-3** [comment]
seen it also ... we are going to check this

**Comment by m-1-k-3** [comment]
update is out there ...

**Comment by torabi12** [comment]
The full installation went through the previous step but it stopped here on my side:

![kép](https://user-images.githubusercontent.com/98665813/208140734-e57d8082-e2ac-4496-8f29-ec3bacd75094.png)
