### ISSUE TITLE
Add Windows CE support

### ISSUE THREAD

**Issue by chatelao** [e-m-b-a/emba#443]
It would be very nice to have a bit Windows CE support:

Example (VoIP Phone) here:
https://www.microsoft.com/en-us/download/details.aspx?id=23866

**Comment by m-1-k-3** [comment]
Currently EMBA has support for Linux and some RTOS systems. At least from our side EMBA has never seen a Windows firmware and probably the results are not that good. It would be very interesting to include basic Windows (CE) Support.

**Comment by m-1-k-3** [comment]
Do we have some established analysis steps for Windows e.g., filesystem extraction

**Comment by m-1-k-3** [comment]
asdf

**Comment by m-1-k-3** [comment]
https://github.com/e-m-b-a/emba/issues/897
