### ISSUE TITLE
Add - CR16C support

### ISSUE THREAD

**Issue by chatelao** [e-m-b-a/emba#448]
**Is your feature request related to a problem? Please describe.**
I have a strange firmware for my "FritzFon" probably running on a SiTel / Dialog SC1844xx chip with a CompactRISC / CR16C instructions set. Ghidra support decompilation of the binary:
- https://download.avm.de/dect/0802/psq19p2/08.02.04.67.avm.de.upd

**Describe the solution you'd like**
If there would be a way to simulate the boot operation on the phone would be great. No idea if there are any CR16C emulators out there.

**Comment by m-1-k-3** [comment]
Very interesting. Is this architecture supported from objdump or r2?

**Comment by m-1-k-3** [comment]
As far as I can see on a first check EMBA is not able to extract the firmware

![image](https://user-images.githubusercontent.com/497520/210617288-cb2dfcb4-23c3-4580-9adc-ed698f434922.png)

Freetz-NG neither

![image](https://user-images.githubusercontent.com/497520/210617333-eaa42b4c-4c32-4a70-9f2b-7a58d57af25b.png)

What are your steps to extract it?

**Comment by m-1-k-3** [comment]
Further details on this issue?

**Comment by m-1-k-3** [comment]
Please re-open it with further details.
