### ISSUE TITLE
Error detected - status code 100 Command:  echo -e "Command:  $ORANGE$BASH_COMMAND$NC"

### ISSUE THREAD

**Issue by d4op** [e-m-b-a/emba#456]
Everywhere in all scripts where:
echo -e "Command:  $ORANGE$BASH_COMMAND$NC"
is located. the run breaks here with error:

Error detected - status code 100
Command:  echo -e "Command:  $ORANGE$BASH_COMMAND$NC"

bash / zsh

**Comment by d4op** [comment]
can be closed. bug was triggered because of a apt repo which throw an error in apt update.
your script broke after this.

**Comment by m-1-k-3** [comment]
thank you
