### ISSUE TITLE
Status bar rendering stability

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#461]
**Describe the bug**

The EMBA status bar (activation with -B parameter) does not regenerate correctly on changing the screen size.

**To Reproduce**
1. EMBA installation (default mode)
2. Use the firmware available here: random firmware
3. Start EMBA with the following parameters: `sudo ./emba.sh -f ~/firmware-stuff/Firmware_images/testimages/web -l ~/firmware-stuff/emba_logs_test -S -p ./scan-profiles/default-scan.emba -B` -> -B parameter is important
4. Wait for EMBA startup and the status bar appears
![image](https://user-images.githubusercontent.com/497520/214806657-fb5e925b-6c4e-4c36-9233-b42f1b34a771.png)
6. Change window size with mouse to bigger and something smaller and the status bar does not regenerate correctly anymore
![image](https://user-images.githubusercontent.com/497520/214806817-b1ef2a93-8644-49e5-90b3-237847abebdf.png)
![image](https://user-images.githubusercontent.com/497520/214807092-f1733f4a-9b94-44fe-83e7-e6962977754f.png)
![image](https://user-images.githubusercontent.com/497520/214807132-60b539f6-38ce-4f22-b09b-e6997a963f96.png)

**Expected behavior**
Stable status bar

**Screenshots**
see above

**Desktop:**
- OS: e.g. Kali Linux 2022.03
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
Need to debug this in detail soon

**Comment by torabi12** [comment]
Easy to reproduce:
- please start an emba scan with default-profile in terminal window size, wait a few minutes to see the bar with values and change the terminal size to full size. The status bar will be empty in the bottom for the remaining scan progress.

**Comment by m-1-k-3** [comment]
In my testing szenario it is not that ugly but it looks as the calculation of the terminal size somehow breaks

Before:

![image](https://github.com/e-m-b-a/emba/assets/497520/7058e97b-ade8-4411-801d-7ccf9acb5a0f)

After:

![image](https://github.com/e-m-b-a/emba/assets/497520/9b6a8488-0f74-4e0f-942f-6e8cd9d15ead)

Fixing this will probably take a while as I'm quite busy with other things ...

**Comment by torabi12** [comment]
Yes, this is the initial state, but if you wait more while the test is running the CPU, MEM graphs will fill up the screen. Or it can happen like on my side.
It is not critical, I just wanted to mention it.
