### ISSUE TITLE
Check system memory and warn if < 4GB

### ISSUE THREAD

**Issue by eacmen** [e-m-b-a/emba#486]
**Is your feature request related to a problem? Please describe.**
I was trying to use emba and the cve_search module always threw an error. Deeper inspection revealed a ton of Redis exceptions (connection reset, connection refused) in the db_updater.py code. Some hours of debugging later on revealed that was hitting an upper limit as the kali VM I imported only had 2GB of RAM by default. 

Sorry I don't have copies of the exact exceptions I was getting.

**Describe the solution you'd like**
When installing or running cve-search module recommend checking system memory and issuing a warning if the system has less than 4GB of RAM.

**Describe alternatives you've considered**
none

**Additional context**
Great tool. Thanks!

**Comment by m-1-k-3** [comment]
Thats a very good idea. As we already have a warning if there is not enough disk space such an additional check totally makes sense

**Comment by m-1-k-3** [comment]
Did a quick fix in the next PR here https://github.com/e-m-b-a/emba/pull/485

Thanks for your report.

**Comment by eacmen** [comment]
wow that was quick. thank you! ill test it out when i get a chance.
