### ISSUE TITLE
Firmware vendor parameter

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#491]
**Describe the bug**
I wanted to run a test with the parameters X, Y, Z and N, but at the beginning it quit with the following error:
![image](https://user-images.githubusercontent.com/98665813/221131344-5dedf101-3d29-4735-a20c-bc218140f04c.png)

If I do not specify the parameters, the test will run correctly.
I tried EMBArk also with filled versions and vendor names and all my tries were failed, the tests did not start:

![image](https://user-images.githubusercontent.com/98665813/221132685-6170c4dc-5a0d-487a-8743-bff7d8c690da.png)

**To Reproduce**
1. EMBA installation (default mode)
2. Use the firmware available here: any
3. Start EMBA with the following parameters: sudo ./emba -X "V01.00.100" -Y "Vendor" -Z "Device_01" -N "file.bin"

**Expected behavior**
I would like to receive information on what is allowed to enter in the quotation marks.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: Kali Linux 2022.4 / Ubuntu Server 22.04.1
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
We changed the input validation a while ago ;) Could you try `-Y Vendor `
-> -Y allows alphanummeric input
-> -Z allows alphanummeric input
-> -N allows alphanummeric input

I will update the help output. thank you for reporting
