### ISSUE TITLE
Failed to create shim task

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#493]
**Describe the bug**
At the beginning emba scan stopped with these errors:

![image](https://user-images.githubusercontent.com/98665813/221144283-27c908e4-2f31-4ac7-a3c8-def11c4d5c37.png)

I have executed a scan before for this file and it used to work.

**To Reproduce**
1. EMBA installation default mode
2. Use the firmware available here: pivot_bfa.bin
3. Start EMBA with the following parameters: sudo ./emba -l ~/Pivot -f ~/pivot_bfa.bin -p ./scan-profiles/default-scan.emba -Y PivotProject

**Expected behavior**
Test should go on.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: Kali Linux 2022.4
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
duplicate from https://github.com/e-m-b-a/emba/issues/489
