### ISSUE TITLE
pip packages on latest Kali

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#508]
**Describe the bug**
I got some errors on the latest Kali for the following packages:
![kép](https://user-images.githubusercontent.com/98665813/222710738-66875ecb-8583-42e3-b9e2-219ece20dce8.png)

![kép](https://user-images.githubusercontent.com/98665813/222710759-dd895748-41f4-45c9-9e25-76c4e242696d.png)

![kép](https://user-images.githubusercontent.com/98665813/222710777-7d1aa316-1b69-4c44-af49-9b1c79e297f9.png)

I wanted to fix them by manually, but it was not working:

![kép](https://user-images.githubusercontent.com/98665813/222710873-6e1266b6-4a40-44e8-ba3b-6fc967b7d610.png)

If the issue is not relevant please ignore it, I just wanted to collect and mention what is happening on a new installation with a brand new Kali linux.

**To Reproduce**
1. EMBA installation default mode
2. See errors

**Expected behavior**
If it can be fixed please give me some advice.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: Kali Linux 2022.4
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
You should be able to install packages with the additional parameter `--break-system-packages`
See also here: https://github.com/e-m-b-a/emba/blob/2285e2aedeb37138455bca30df3a74b7d3ebd040/installer/helpers.sh#L174

**Comment by torabi12** [comment]
I tried these packages and I didn't get the warnings during the new emba installation:

$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed aioconsole==0.3.3
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed lsassy==3.1.4
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed minikerberos==0.3.3
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed neo4j==4.4.10
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed pypsrp==0.7.0
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed pywerview==0.3.3
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed xmltodict==0.12.0
$ sudo pip3 install --force-reinstall --break-system-packages --no-deps --ignore-installed pyee==8.2.2

**Comment by m-1-k-3** [comment]
see https://github.com/e-m-b-a/emba/issues/568
