### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dragosmanolea** [e-m-b-a/emba#520]
**Describe the bug**
I tried to run the docker-compose build command and i had an error during building: Job for redis-server.service failed because a timeout was exceeded.

**To Reproduce**
1. EMBA build docker-compose
2. Fail at installation

**Expected behavior**
Build image successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/45299314/224252993-70c2906d-e107-4610-9549-745ccf70feec.png)

**Desktop (please complete the following information):**
- OS: Ubuntu Server 20 VM
- EMBA version: v1.2.1
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
For using EMBA I recommend to use the provided docker images. This is automatically installed by the installer via `sudo ./installer.sh -d`

For building the EMBA image from scratch you need to run `sudo docker-compose build --no-cache --pull` on a current Kali or Ubuntu 22.04 LTS

**Comment by dragosmanolea** [comment]
When i tried to use the provided docker images, i had some problems during runtime. I opened an issue before.

**Comment by m-1-k-3** [comment]
I think this issue is handled via https://github.com/e-m-b-a/emba/issues/519
