### ISSUE TITLE
Docker-compose.yml is invalid

### ISSUE THREAD

**Issue by dragosmanolea** [e-m-b-a/emba#521]
**Describe the bug**
When I tried to build the docker-compose i got this error: The compose file './docker-compose.yml' is invalid because:
networks.emba_runs value Additional properties are not allowed ('name' was unexpected)

**To Reproduce**
1. Clone the repo
2. Run docker-compose build

**Expected behavior**
Build should work.

**Screenshots**
<img width="694" alt="image" src="https://user-images.githubusercontent.com/45299314/224253860-7aa1c025-90d3-48f9-836b-e4ed6bda5e83.png">

**Desktop (please complete the following information):**
- OS: Ubuntu Server 20 VM
- EMBA version: v1.2.1
- Installation method: default with up to date docker image

**Comment by m-1-k-3** [comment]
Are you using Ubuntu 22.04 LTS as host? Please check the https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

**Comment by dragosmanolea** [comment]
No, I have another host.
My fault here.

**Comment by m-1-k-3** [comment]
I think this issue is handled via https://github.com/e-m-b-a/emba/issues/519
