### ISSUE TITLE
Custom Wordlist question

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#522]
I would like to use custom wordlist file for emba scans.
I created the jtr_wordlists.txt file in ~/emba/config folder and I put the path of the wordlist file, like:
/usr/share/wordlists/rockyou.txt

I would like to ask you is it OK to enter the path of the custom file or I need to put the entire wordlist into the jtr_wordlists.txt?
If the path is OK, may I add more wordlist files?

**Comment by m-1-k-3** [comment]
You need the complete wordlist in there.
