### ISSUE TITLE
CVS export S12

### ISSUE THREAD

**Issue by keesj** [e-m-b-a/emba#551]
Hello,

The CSV files created by emba are not of the best quality. Sometimes information is missing and sometime like for F50 different rows have a different amount of entries. This makes is a bit hard to use the data. in csv_logs/s12_binary_protection.csv  something different is happening. The header contains 9 entries (FILE being the last one) but the rows of the data contain 2 additinal values (numbers)

Can you please either document the additinonal numbers by adding a header entry for them or remove them from the CSV?

**Comment by m-1-k-3** [comment]
f50 csv is only for EMBArk. The s12 is fixed in #553 

Thanks for reporting.

**Comment by m-1-k-3** [comment]
f50 should be also adjusted in this PR.
