### ISSUE TITLE
crackmapexec python package error

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/emba#568]
**Describe the bug**

**To Reproduce**
1. EMBA installation default apps_host

**Expected behavior**
installation without errors or warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/62940240/229781137-7519b5e8-05d2-4313-a9af-c319473d56b9.png)

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.01
- EMBA version: current master branch
- Installation method: default

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by torabi12** [comment]
Similar dependencies have been mentioned here:
https://github.com/e-m-b-a/emba/issues/508

**Comment by m-1-k-3** [comment]
Does this affect EMBA beside the error message?

**Comment by torabi12** [comment]
Anyone who doesn't know exactly how these work and installs EMBA will be scared to death that there is a bug in the system:)

**Comment by m-1-k-3** [comment]
harhar ... if there is no real defect I can live with this ;)

**Comment by m-1-k-3** [comment]
If you do not need [crackmapexec](https://wiki.porchetta.industries), e.g., if you are using your Kali box only for _EMBA_ you should be save to uninstall `crackmapexec` the following way:

```
   └─$ sudo apt-get remove crackmapexec -y
```

btw. this is the default VM from kali:

![image](https://user-images.githubusercontent.com/497520/235365594-86e5a9c6-4644-4727-9d22-91895f0c183a.png)

Which means that this is definitive not an EMBA issue. From EMBA side this is closed but I will leave this issue open for reference and that others will find it easily.
