### ISSUE TITLE
EMBA failing in docker mode

### ISSUE THREAD

**Issue by keeplearning-rgb** [e-m-b-a/emba#577]
I am facing this issue while trying to scan the files using EMBA.

I tried re installing EMBA several times but still facing this issue.

Please have a look at this and let me know how to fix it.

![image](https://user-images.githubusercontent.com/72157228/230890488-609bdafa-f5e7-4fe9-8a8e-78f3cd7e32d9.png)

**Comment by m-1-k-3** [comment]
I don't get this screenshot. The latest docker image has all these prerequisites included. Could you please give more details on your steps to get this output?

**Comment by keeplearning-rgb** [comment]
This is after installing latest version of EMBA. while trying to run it on a bin file. I am getting this output

sudo ./emba.sh -f /root/Desktop/P3225-LVE_Mk_II_9_80_3_13.bin -l ~/Documents/projects/p3225_log/ -p ./scan-profiles/default-scan-emulation.emba

This is the command i have used

**Comment by m-1-k-3** [comment]
a ... yes, now I see your issue. You are using the EMBArk version? Please update the EMBA installation as documented here: https://github.com/e-m-b-a/embark/issues/110#issuecomment-1500885694

**Comment by keeplearning-rgb** [comment]
You want me to replace the file in helpers module and re run the installation

**Comment by m-1-k-3** [comment]
you can do a `git submodule update --remote` or you can change the helper script manually

**Comment by keeplearning-rgb** [comment]
Running git command didn't worked for me but updating the helpers module worked.
Thanks for the quick help.
Can't this be fixed at root level in EMBA repository so that we don't get this error while using installer.sh .

Also, if you can let me how can i install a specific version of EMBA without this version mismatch.

**Comment by m-1-k-3** [comment]
We are going to fix this the next days also in EMBArk. If you just want to run EMBA without EMBArk you can install EMBA manually in a separate directory without the mismatch.

**Comment by keeplearning-rgb** [comment]
Thanks for the update
I think i am still facing some issues with the same. I will update you here once it is working properly

**Comment by keeplearning-rgb** [comment]
I am separately using EMBA for now. its working fine. 
I will delete my embark folder and see the fix you have provided works or not.
Please close the issue for now if required i will reopen it
