### ISSUE TITLE
Worklfow problem

### ISSUE THREAD

**Issue by BenediktMKuehne** [e-m-b-a/emba#578]
![image](https://user-images.githubusercontent.com/62940240/231764930-75683bd7-0e80-4238-9e57-c694bbcf693d.png)

[Actions](https://github.com/e-m-b-a/emba/actions/workflows/default_install.yml)

Also affects EMBArk

**Comment by BenediktMKuehne** [comment]
testing this here first [EMBArk-PR](https://github.com/e-m-b-a/embark/pull/117)

**Comment by m-1-k-3** [comment]
further notes https://github.com/jlumbroso/free-disk-space/issues/4

**Comment by m-1-k-3** [comment]
Update: The recommended fix is not working as expected
![image](https://user-images.githubusercontent.com/497520/232080777-d3a16fef-472e-4543-947b-d7adbea9d1d8.png)
