### ISSUE TITLE
CycloneDX SBOM missing numerous identified components

### ISSUE THREAD

**Issue by n0x08** [e-m-b-a/emba#588]
**Describe the bug**
The CycloneDX SBOM file does not contain all identified components with their respective versions.

**To Reproduce**
1. EMBA installation: default mode + git pull on April 11th 2023
2. Use the firmware available here: https://share.netmodule.com/public/system-software/4.6/4.6.0.104/NB3800_Software_Release_4.6.0.104.img
3. Start EMBA with the following parameters: sudo ./emba.sh ~/NB3800_Software_Release_4.6.0.104.img -l ~/NB3800_Software_Release_4.6.0.104 -p ./scan-profiles/default-scan.emba
4. View HTML report
5. Compare the list of "Identified software components - via usermode emulation." to what is in "CycloneDX SBOM converter" and you will see many components are missing.

**Expected behavior**
I would expect that all components with an identified version would be listed in the SBOM

**Screenshots**
Identified components:
![image](https://user-images.githubusercontent.com/34355466/232580241-bc0c3c67-2b1e-4f7f-9acf-b7059109827a.png)

CycloneDX file (notice bgpd is missing; this is just one example)
![image](https://user-images.githubusercontent.com/34355466/232580393-ffe10a49-9f8d-4993-b1b5-3cc48e02304e.png)

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04
- EMBA version: v1.2.2 or current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [Y/N]

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
looks like f20 is only reporting software components with vulnerabilities to csv. This results in missing components in the sbom.
