### ISSUE TITLE
Kali Linux 2023.2 support

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#645]
New Kali Linux is out: https://www.kali.org/blog/kali-linux-2023-2-release/

We need to test EMBA on it

**Testcases:**

Testfirmware: [DLink DIR300](https://ftp.dlink.de/dir/dir-300/archive/driver_software/DIR-300_fw_revb_214b01_ALL_de_20130206.zip)

- [x] Default/docker installation working with current docker image (`./installer.sh -d`)
  - [x] dependency check (`./emba.sh -d 1`)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)
- [x] Full installation working (`./installer.sh -F`)
  - [x] dependency check (`./emba.sh -d 1`)
  - [x] EMBA run in dev mode with options -s -z -S -D -E -t -W -Q
  - [x] EMBA run in dev mode with options -s -z -S -D, -c, -E, -t, -W -Q
- [x] Docker build (`sudo docker-compose build --no-cache --pull`)
  - [x] dependency check (`./emba.sh -d 2`)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)

**Comment by torabi12** [comment]
Test env: VMWare Workstation Pro 17.0.2 & Kali 2023.2

Before emba installation I removed the
```
$ sudo apt purge openvas-scanner
$ sudo apt purge crackmapexec
```
packages. 

1st installation process was OK, CVE data came withput error, I only get some warning about pip packages:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/c3145d3b-8f2f-4f58-b6f6-1dab0c6d3da3)
Maybe these versions would be OK:

```
pyee==8.2.2
impacket==0.9.24
rich==10.16.2
```

- default-scan in strict mode was this:
`./emba -l /home/seclab/Kankun -f /home/seclab/kkeps.bin -S -p ./scan-profiles/default-scan.emba -X 1.0 -Y Kankun -Z Smartplug -N kkeps.bin`

I used a custom jtr_wordlist.txt file and john has also cracked the found hashes, report was OK.

- default-scan-emulation in strict mode is running right now but this failure comes back all the time:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/b8a8046f-9e2b-4ba0-be51-6d38f4c64d48)

I am using a WNAP320 fw which is easy to use with` ./fat.py` to get the dynamic analysis. I let it run for a while but it looks like the process is hanging at the above error.
The fw WNAP320_V2.0.3.zip can be found here:
https://www.netgear.com/support/product/wnap320#download

**Comment by m-1-k-3** [comment]
The error looks like an error from the original S045_lighttpd.sh script in line 40. This should not stop EMBA. I will give it a try.

**Comment by m-1-k-3** [comment]
we changed the startup handling of services in the last updates. Witch this we are able to cover more startup services. So, this error could be quite new :)

**Comment by m-1-k-3** [comment]
The S120 module is currently not working in full-install aka dev mode. I will open a dedicated issue for this. But, as EMBA should be used in docker/default mode this issue is not critical.

Thanks for testing efforts @torabi12
