### ISSUE TITLE
cwe_checker modul does not work in expert mode

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#653]
**Describe the bug**
I used expert mode in EMBArk for a D-Link FW. I selected all the modules except S99 and S110.
The EMBA start command was this according to the report:

EMBA start command: /var/www/emba/emba -p ./scan-profiles/default-scan-no-notify.emba -f /var/www/active/b200dae0-a940-4de9-b8a5-5d720e9b5cf5/dcs932l_v1.14.04.bin -l /var/www/emba_logs/b200dae0-a940-4de9-b8a5-5d720e9b5cf5/emba_logs -X 1.14.04 -Z DCS-932L -Y D-Link -N CWE test (uuid:b200dae0-a940-4de9-b8a5-5d720e9b5cf5) -a MIPS -m s02 -m s03 -m s05 -m s06 -m s08 -m s09 -m s10 -m s12 -m s13 -m s14 -m s15 -m s20 -m s21 -m s22 -m s24 -m s25 -m s35 -m s40 -m s45 -m s50 -m s55 -m s60 -m s65 -m s70 -m s75 -m s80 -m s85 -m s90 -m s95 -m s100 -m s106 -m s107 -m s108 -m s109 -m s115 -m s116 -m s120

but the report generated by EMBArk does not contain the cwe-checker section.

I executed the same test in emba with this init command:
![image](https://github.com/e-m-b-a/embark/assets/98665813/49976dd4-9ada-43ca-ab84-a55e72b954be)

The cwe section is available in the main page:
![image](https://github.com/e-m-b-a/embark/assets/98665813/7af1beed-6264-46c7-b976-9de90956e79d)

but on emba side if I would like to open the details:
/html-report_emba/s120_cwe_checker.html

the page is not available:
![image](https://github.com/e-m-b-a/embark/assets/98665813/10a5baf4-a120-4994-ae0f-e7db367ad0c3)

Sorry for mixing the two issues but on EMBArk side the S120 modul does not work and the report generation maybe not OK for the same modul in emba.

**To Reproduce**
1. EMBArk installation (default mode/docker-mode)
2. Start EMBArk: sudo ./run-server.sh
3. Use the firmware available here: https://drivers.softpedia.com/get/network-ip-surveillance-baby-camera/D-Link/D-Link-DCS-932L-rev-A-IP-Camera-Firmware-1-14-04.shtml
4. Try to run S120 modul.
5. Missing CWE-checker output in the report.

**Expected behavior**
- EMBArk should run S120 and write the output to the report.
- emba should create and display the S120 subpage.

**Screenshots**
I followed the actual moduls running in logreader file for EMBArk and S120 was not on the list:
![image](https://github.com/e-m-b-a/embark/assets/98665813/7330ceab-1e7e-4c5a-911f-95b2757e0f2d)

**Desktop (please complete the following information):**
 - OS: 2023.01 for emba and Ubuntu Server 22.04.02 for EMBArk

**Additional context**
I attached the full report from EMBArk:
[html-report_EMBArk.zip](https://github.com/e-m-b-a/embark/files/11563125/html-report_EMBArk.zip)

**Comment by m-1-k-3** [comment]
This is an EMBA issue. We will handle it here
