### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by gaohang** [e-m-b-a/emba#685]
**Describe the bug**
I came across below problem when run "sudo ./install.sh -d"
ubuntu 20.04

[+] I01_default_apps_host
=================================================================

To use EMBA, some applications must be installed and some data (database for CVS for example) downloaded and parsed.

These applications will be installed/updated:

jq
Description: lightweight and flexible command-line JSON processor
Download-Size: 未知
------------------------------------------------------------------------------------------------
Error detected - status code 1
Command:  UPDATE=$(LANG=en apt-cache policy "$1" | grep -i install | cut -d: -f2 | tr -d "^[:blank:]" | uniq | wc -l)
Location:  ./installer/helpers.sh, line 67
Stack Trace:
    [1] print_tool_info(): ./installer/helpers.sh, line 67 -> print_tool_info jq 1
    [2] I01_default_apps_host(): ./installer/I01_default_apps_host.sh, line 24 -> I01_default_apps_host
    [3] main(): ./installer.sh, line 260 -> main -d

**Expected behavior**

**Comment by m-1-k-3** [comment]
Please check our prerequisites and use Ubuntu 22.04 LTS for EMBA: https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites
