### ISSUE TITLE
Display the analysis time in the final aggregator

### ISSUE THREAD

**Issue by n0x08** [e-m-b-a/emba#697]
**Describe the solution you'd like**
I would like to see the overall time it took to analyze the firmware image displayed in the final aggregator page. Per-module analysis time could be good too as it would help me tune which modules to exclude from my scans when I want to process many images.

**Describe alternatives you've considered**
Currently I use 'time <emba command>'

**Priority issue**
Low priority

**Additional context**
An example of how this could look:
[+] Final aggregator
[+] Tested firmware: /home/nate/Polycom_3111-48820-021.sip.ld
[+] EMBA start command: ./emba -f /home/nate/Polycom_3111-48820-021.sip.ld -l /home/nate/Polycom_3111-48820-021 -p ./scan-profiles/default-scan.emba
[+] Detected architecture and endianness (verified): ARM / EL
 
[+] Operating system detected (verified): Linux / v4.19.0
[+] Total analysis time: 804 minutes

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
Just to ensure I understand you correct. You need the testing time in the final report? I'm asking as the scan time is already shown in multiple areas:

![image](https://github.com/e-m-b-a/emba/assets/497520/72778493-1157-4faf-8132-d1dd4fc99c80)

You can access this information also from the web reporter:

![image](https://github.com/e-m-b-a/emba/assets/497520/82f4a819-6886-4932-bcc4-0b6bb664a51b)

![image](https://github.com/e-m-b-a/emba/assets/497520/2c2f37f0-f474-4fdc-9571-3831b1485711)

**Comment by n0x08** [comment]
Ooops :) I should have looked around more, that's exactly what I was looking for! Thank you!

**Comment by m-1-k-3** [comment]
I think we can close this. If not, please re-open it again.
