### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#716]
**Describe the bug**
During the installation I got some warnings and errors. See screenshot section.

**To Reproduce**
1. EMBA installation (default mode)
2. See error

**Expected behavior**
404 should be 200.

**Screenshots**
![kép](https://github.com/e-m-b-a/emba/assets/98665813/e948a2e1-0283-483f-86ba-6fe04d0f806e)

![kép](https://github.com/e-m-b-a/emba/assets/98665813/32eb1fbd-d72a-4705-a6ba-656c15bc7137)

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.02
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**
I wanted to update the previous emba installation and ./emba_updater was not working fine on my side, after this I made a new clean installation and I got the above messages.

**Comment by m-1-k-3** [comment]
EMBA is trying multiple libssl download possibilities. Are all these tries resulting in a 404 or is it working on some stage? It shoudl try version 18.04.21 till 18.04.29. Is the installation finished and working?

**Comment by torabi12** [comment]
EMBA updater drops this:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/70ed7cfa-176b-4a16-9ba3-5dadc7dab5e5)

The installation went at the end and the scanning looks fine, but I just started a few minutes before.

**Comment by m-1-k-3** [comment]
The updater looks not good

**Comment by torabi12** [comment]
I found the updater error first, and after that I did a clean install and just wanted to mention the warnings, but the scan is running fine now.

**Comment by m-1-k-3** [comment]
looks good on a fresh install

![image](https://github.com/e-m-b-a/emba/assets/497520/db1203ad-6782-4363-987e-f38ed765219e)

**Comment by torabi12** [comment]
The update script still drops the same error for me:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/73e7dc80-30d6-427e-8c62-6aa01c83adfc)
