### ISSUE TITLE
why sbom file has not cpe and purl item？

### ISSUE THREAD

**Issue by chenjianquan7** [e-m-b-a/emba#734]
**Describe the bug**
i use emba analysis firmware , result an sbom json file ,but it has not cpe and purl item, why?
only name and version.
![image](https://github.com/e-m-b-a/emba/assets/26828709/d801fe3e-cb74-413d-a831-4b2d92a9846c)

**To Reproduce**
1. EMBA installation (dev-mode/default mode)
2. Use the firmware available here: <Insert URL>
3. Start EMBA with the following parameters: sudo ./emba.sh <insert further parameters>
4. additional steps
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: e.g. Kali Linux 2023.01
- EMBA version: v1.2.2 or current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [Y/N]

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
Currently no one has implemented it ;) PR are welcome

**Comment by m-1-k-3** [comment]
problem solved? Anything else we can support you?
