### ISSUE TITLE
it return error "ImportError: cannot import name 'ContextAPI' from 'docker'" when install

### ISSUE THREAD

**Issue by chenjianquan7** [e-m-b-a/emba#735]
**Describe the bug**
![image](https://github.com/e-m-b-a/emba/assets/26828709/0b390c45-e06e-45fb-8622-b40448e20d6d)

**To Reproduce**
1. EMBA installation (dev-mode/default mode)
2. Use the firmware available here: <Insert URL>
3. Start EMBA with the following parameters: sudo ./emba.sh <insert further parameters>
4. additional steps
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: e.g. Kali Linux 2023.01
- EMBA version: v1.2.2 or current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [Y/N]

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
Can you provide more details?

**Comment by m-1-k-3** [comment]
any updates? Otherwise it will get closed.
