### ISSUE TITLE
emba update drops errors

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#742]
**Describe the bug**
After a clean installation of the latest emba I tried the emba_updater script but it did not work for me. Please see the screenshot of it.

**To Reproduce**
1. EMBA installation default mode
2. Reboot
3. Start emba_updater script as root

**Expected behavior**
DB update should start without any error.

**Screenshots**

Update:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/b61b69be-c337-4c99-b607-41729479e6b4)

End of default installation:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/1a3109b6-e4ff-4952-a1db-5d4adbef45b9)

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.02
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Comment by BenediktMKuehne** [comment]
Had the same thing happening yesterday, installation succeeded though. And the dependency check does too.

**Comment by torabi12** [comment]
I tried it for the 3rd time and I got the same error at the end of installation, CAPEC download was not working and after the reboot the update script was not OK.

**Comment by m-1-k-3** [comment]
Looks like some issue with the new pipenv environment

**Comment by m-1-k-3** [comment]
The CAPEC error should be fixed on cve-search side here https://github.com/cve-search/cve-search/releases/tag/v4.2.2 -> we need to update it soon

**Comment by m-1-k-3** [comment]
The newest cve search version should be used now. Please check it and report if there are any issues. I will dig deeper into the update issue as soon as I'm back.

**Comment by torabi12** [comment]
Hello,

I modified the line 40 in IF20_cve_search.sh to get the actual cve-search:
`git clone https://github.com/cve-search/cve-search.git external/cve-search`

and did a default installation. The installation went well:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/e34a5003-89c5-482f-991d-8a893f2e06b4)

and the CAPEC also downloaded:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/527c9382-01a1-4c50-91c6-fa95bcd0333d)

I started a scan which will take some time but the beginning looked fine:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/a61821d3-667c-4ad6-b0e9-61cebb72cc77)

Please let me know if there is a better way to test the cve-search with e-m-b-a.

**Comment by m-1-k-3** [comment]
The installer should already use the latest cve search. Give it a try without your modifications

**Comment by torabi12** [comment]
The installation works fine in the untouched state.
