### ISSUE TITLE
how to work for sbom only?

### ISSUE THREAD

**Issue by chenjianquan7** [e-m-b-a/emba#744]
i am use emba analysis firmware, then output sbom file.
now i want decrease time,  is it analysis sbom only ?  i wantnot cve etc.

**Comment by m-1-k-3** [comment]
You could use the SBOM profile sbom-default.emba

**Comment by m-1-k-3** [comment]
I will close this for now. If further assistence is needed please reopen it

**Comment by m-1-k-3** [comment]
should be addressed in PR #1323
