### ISSUE TITLE
Inconsistent Scanning Results and Duration for Same File

### ISSUE THREAD

**Issue by qingyuanyou** [e-m-b-a/emba#756]
Describe the bug:
I am encountering an issue during scanning where the results and duration vary significantly under similar conditions.

Expected behavior:
I expected consistent scanning results and duration for the same input.

Additional context:
The time taken to complete scans of the same file (around 60M) significantly differs, ranging from around several hours to several days.
Scanning the headers of the same TBox yields inconsistent results – one scan produces CVE results, while another does not.
I am seeking guidance on resolving this issue and determining which set of results should be considered accurate and what is the cause of this problem.  Your assistance is greatly appreciated.

**Comment by m-1-k-3** [comment]
It would be interesting to get more details:
* Both tests performed on the same box with the same EMBA checkout?
* Both tests performed with the same docker image?
* Multiple EMBA tests on the same box during this time period or exclusive this one test?
* Which parameters you were using for the EMBA startup?
* Where can we access the firmware file?
* Can you share both reports for further analysis?

**Comment by qingyuanyou** [comment]
Hi Team,
We found out that the problem was caused by a lack of disk space.
Thanks for your support.
