### ISSUE TITLE
Kali Linux 2023.03 is out now

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#767]
New Kali Linux is out: https://www.kali.org/blog/kali-linux-2023-3-release/

We need to test EMBA on it

**Testcases:**

Testfirmware: [DLink DIR300](https://ftp.dlink.de/dir/dir-300/archive/driver_software/DIR-300_fw_revb_214b01_ALL_de_20130206.zip)

- [x] Default/docker installation working with current docker image (`./installer.sh -d`)
  - [x] dependency check (`./emba.sh -d 1`)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)
- [x] Full installation working (`./installer.sh -F`)
  - [x] dependency check (`./emba.sh -d 1`)
  - [x] EMBA run in dev mode with options -s -z -S -D -E -t -W -Q
  - [x] EMBA run in dev mode with options -s -z -S -D, -c, -E, -t, -W -Q
- [x] Docker build (`sudo docker-compose build --no-cache --pull`)
  - [x] dependency check (`./emba.sh -d 2`)
  - [x] EMBA run with profile default-scan in strict mode (-S)
  - [x] EMBA run with profile default-scan-emulation in strict mode (-S)
  - [x] EMBA run with profile full-scan in strict mode (-S)

**Comment by torabi12** [comment]
I would do the default/docker installation and tests on the weekend with the latest Kali.

**Comment by torabi12** [comment]
- Installation was OK with the current master release.
- Dependency check gave me this message more times:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/80fa002c-e974-46f8-ab6a-cbcb124ccce1)

- default-scan in strict mode (-S) started but gave back back prompt at the beggining with this message:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/7860fb6c-2f59-494a-a4a9-c4a39f18b22f)

This was the init command:
`$ sudo ./emba -l ~/DIR300_default -f ~/DIR300B5_FW214WWB01.bin -p ./scan-profiles/default-scan.emba -S -X 2.14 -Y D-Link -Z DIR-300 -N DIR300B5_FW214WWB01.bin`

Could you help what to try for better results?

**Comment by m-1-k-3** [comment]
this is the messaging system. Looks like something changed under the hood. I need to take a look at this. Is the scan starting up in "non-strict" mode (remove -S option)?

**Comment by torabi12** [comment]
Without -S the scan has started. It displayed the same errors but went on and now it is running....

**Comment by m-1-k-3** [comment]
ok, this means a normal EMBA user is not directly affected. I will check on this

**Comment by torabi12** [comment]
Default scan is finished, report looks fine. The above error came at the end also:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/e79f7991-cc4f-4bb7-8c32-bb7a7e130570)

I would wait for any updates for dbus-launch message with the next scans.

**Comment by torabi12** [comment]
> Looks like we need to install the following package:
> 
> ```
> sudo apt install dbus-x11
> ```
> 
> Can you verify this on your installation?

With dbus-x11 package the dependency check was OK without any error, and the strict-mode default scan has started also now.
I am going to execute the remaining tests on this environment.

**Comment by torabi12** [comment]
I executed the default tests, all in strict mode.

- default-scan
![kép](https://github.com/e-m-b-a/emba/assets/98665813/ebbca535-5e64-4367-a748-eddd31ce350e)

- emulation
![kép](https://github.com/e-m-b-a/emba/assets/98665813/1dac4939-4d28-4e71-9ed3-a1b9a2e94edf)

- full
![kép](https://github.com/e-m-b-a/emba/assets/98665813/8f366386-74ad-4316-a6b3-6753a20fe034)

When the dbus-x11 will be installed with EMBA I will install a new clean release again, but I didn't see other issue under the setup.

**Comment by m-1-k-3** [comment]
Another fix for the dev mode https://github.com/e-m-b-a/emba/pull/777

**Comment by m-1-k-3** [comment]
thx for all your support. Last tests are finished!
