### ISSUE TITLE
Black Screen Issue When Scanning 300M Cabin Package in Docker

### ISSUE THREAD

**Issue by gaolXue** [e-m-b-a/emba#775]
**Describe the bug**
I'm attempting to scan a cabin package of 300M . the program appears to get stuck at the "yara check finished" step, causing my computer screen to go black so that I can only access it via SSH. Is it possible that the scanner cannot execute the hardware emulation when dealing with larger packages?how can I disable the hardware emulation feature? If hardware emulation is turned off, will it affect the ability to generate CVEs?
Thank you!
![image](https://github.com/e-m-b-a/emba/assets/34430631/89d450ae-798b-4902-8e23-43726e9aa20a)
![image](https://github.com/e-m-b-a/emba/assets/34430631/886599e9-2fdd-46ad-9e7e-a73668992b89)

**Comment by m-1-k-3** [comment]
Can you provide a download link from the firmware and your startup command. Additionally, you could check the system log with dmesg ... probably you are running out of memory.

**Comment by gaolXue** [comment]
I'm sorry, but we cannot provide this firmware package. However, I can provide the following information:

We are using the default command for scanning.

Server Information:
CPU: 12th Gen Intel(R) Core(TM) i5-12500
8 cores, 32GB RAM, 2TB storage

Firmware Package Information:
Size: 300MB, contains multiple compressed files
After reversing with emba, it's approximately 7GB in size.

the system configuration is designed to minimize the chances of running into memory issues, I think. And  I will update the system log with dmesg later tonight.

Thanks for your support.

**Comment by m-1-k-3** [comment]
Please check after such a blank screen with `dmesg` for OOM messages.

**Comment by gaolXue** [comment]
updated on my side as below,
there is no error message in system log.
![224ca8a490c4cd7d29f9c7ff2fc5f81](https://github.com/e-m-b-a/emba/assets/34430631/e558a939-e399-4a31-9824-6f8db8313839)
there is the tmp error information.
![322147a957791e311a055870a36317e](https://github.com/e-m-b-a/emba/assets/34430631/024d7224-c878-40b8-b764-171da7e8408a)
Is there any other logs that can help us locate the issue?   or can we just skip the scan model of l10_system_emulation which stuck the process.   if so, please provide the command to skip the model. 
if you need more information, please let me know.
thanks for you support.

**Comment by m-1-k-3** [comment]
According your initial posted logs the module l10 is not started. As you have not provided your startup command I do not know if it should started or not. The logs are somewhere in the scanning phase.

You can check for not finished modules with the following helper script:
```
./helpers/running_modules.sh <Path to your EMBA log directory>
```

Additionally, It looks as you do not use any profile but without further details I do not know.

Are there any out of memory messages printed via dmesg?

Additionally, I would recommend a run in strict mode with parameter -S. Probably we can find an error log in the EMBA log directory afterwards.

**Comment by m-1-k-3** [comment]
Could we have an update on this issue?

**Comment by m-1-k-3** [comment]
reopen if needed
