### ISSUE TITLE
Improve BIOS/UEFI support

### ISSUE THREAD

**Issue by m-1-k-3** [e-m-b-a/emba#780]
**Is your feature request related to a problem? Please describe.**

EMBA is used in a lot of different areas. One of these areas is around BIOS and UEFI analysis. See here: https://www.basicinputoutput.com/2023/08/software-bill-of-materials-sbom-in.html

EMBA has some basic UEFI analysis suppoert (see [here](https://github.com/e-m-b-a/emba/wiki/UEFI-analysis)) but there is a lot of room for improvements and probably we can tweak the results in the future. 

For this we need your support! Please post download links to UEFI and BIOS firmware that we can use for further analysis.
If you have further ideas or solutions to improve BIOS/UEFI analysis in EMBA, please share it here or open a dedicated issue or solution with a pull request.

**Comment by torabi12** [comment]
Server platform might be interesting, this Dell BIOS contains a cap file for testing:
https://dl.dell.com/FOLDER10220002M/1/BIOS_W3X7P_WN64_2.19.1.EXE

Asus is inevitable BIOS provider I think:
https://dlcdnets.asus.com/pub/ASUS/mb/BIOS/PRIME-B560M-K-ASUS-2001.zip

HP is also a huge manufacturer with regular updates on BIOS/FW area:
https://ftp.hp.com/pub/softpaq/sp148001-148500/sp148108.exe

My only experience is that testing is very long if I'm testing UEFI BIOS with EMBA, you can expect to run practically 1 day or more with default settings.

**Comment by m-1-k-3** [comment]
@torabi12 can you provide an EMBA report and the related UEFI firmware from such a long running UEFI test? Probably offline?

**Comment by torabi12** [comment]
I did a scan for the initial version of a Dell server BIOS:
https://www.dell.com/support/home/hu-hu/drivers/driversdetails?driverid=dt5jm&oscode=biosa&productcode=poweredge-r440

[html-report.zip](https://github.com/e-m-b-a/emba/files/13298547/html-report.zip)

but it was just a short test:
Test ended on Wed Nov  8 16:29:49 CET 2023 and took about 0 days and 00:40:04 

I used proxy under this, do you need an offline scan?

**Comment by m-1-k-3** [comment]
@torabi12 if you find some time for testing the improved UEFI handling, your feedback would be very interesting for us :)

**Comment by torabi12** [comment]
> @torabi12 if you find some time for testing the improved UEFI handling, your feedback would be very interesting for us :)

Thanks, I would start a new scan, but I am using the actual master release and I don't know how to move to m-1-k-3:uefi_improvements without reinstalling the system. If you could help it would be faster. :)

**Comment by m-1-k-3** [comment]
probably the easiest way is to clone the branch into a separate directory and link the external directory to your current installation:

```
git clone --branch uefi_improvements https://github.com/m-1-k-3/emba.git emba_test
cd emba_test
ln -s /PATH_TO_YOUR_EXISTING_EMBA_INSTALLATION/external ./external
```

This should be enough :)

**Comment by torabi12** [comment]
Thank you, I started a scan for an older Asus motherboard:
https://dlcdnets.asus.com/pub/ASUS/mb/LGA1151/H110M-A/H110M-A-ASUS-3805.zip?model=H110M-A

Last time this scan was quite long. Tomorrow we will see:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/6a775056-b9d3-416e-ba7f-e6eeb3eb7419)

My OpenAI API key is not the best, it used to work but nowadays is drops quota limit issue:(

**Comment by m-1-k-3** [comment]
as long as you are going to test the cap and not the zip it should work quite well ;)

**Comment by torabi12** [comment]
I used the CAP file for emba, only the download link contains the ZIP format.

**Comment by torabi12** [comment]
Asus BIOS scan was not so long:
![kép](https://github.com/e-m-b-a/emba/assets/98665813/8c556038-cc76-4da8-87ae-56c6b2f7b319)

and the report:
[H110M-A-ASUS-3805_html-report.zip](https://github.com/e-m-b-a/emba/files/13324852/H110M-A-ASUS-3805_html-report.zip)

**Comment by m-1-k-3** [comment]
looks quite good to me. :) Thank you for testing
We need to include it into the deep extractor. With this in place we can also handle archived firmware in the future

**Comment by torabi12** [comment]
Thanks for the help with the test.
