### ISSUE TITLE
Debian11.7.0 issues

### ISSUE THREAD

**Issue by V33RU** [e-m-b-a/emba#805]
Errros encountered while installing emba  in debian 11 ,

EMBA docker image will be downloaded.
CONTAINER VARIABLE SET TO embeddedanalyzer/emba:latest
latest: Pulling from embeddedanalyzer/emba
Digest: sha256:a4bf71cad91063208c5e8b163fd885960c9c9ba29e8507b68ddb3a62cc22a2b6
Status: Image is up to date for embeddedanalyzer/emba:latest
docker.io/embeddedanalyzer/emba:latest
WARNING: The FIRMWARE variable is not set. Defaulting to a blank string.
WARNING: The LOG variable is not set. Defaulting to a blank string.
WARNING: The EMBA variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.emba_runs value Additional properties are not allowed ('name' was unexpected)
------------------------------------------------------------------------------------------------
Error detected - status code 1
Command:  echo -e "Command:  $ORANGE$BASH_COMMAND$NC"
Location:  ./installer/I05_emba_docker_image_dl.sh, line 55
Stack Trace:
    [1] I05_emba_docker_image_dl(): ./installer/I05_emba_docker_image_dl.sh, line 55 -> I05_emba_docker_image_dl
    [2] main(): ./installer.sh, line 310 -> main -d

Important: Consider filling out a bug report at https://github.com/e-m-b-a/emba/issues

**Comment by m-1-k-3** [comment]
Thanks for reporting. Could this be the same issue reported here: https://github.com/e-m-b-a/emba/issues/247

**Comment by alexandruchirita4192** [comment]
Hi,

I wanted to add that I was able to run `emba` on Debian 12.1 with the following commands:
```
git clone https://github.com/e-m-b-a/emba.git
cd emba
sudo ./installer.sh -d
sudo ./emba -l ~/log -f /lib/firmware -p ./scan-profiles/default-scan.emba
```

Maybe you could upgrade your Debian version and retry running emba?

Screenshot to prove that it run successfully on Debian 12.1:
![image](https://github.com/e-m-b-a/emba/assets/34884567/4e4facd4-3d58-4d50-b8cd-d89ed67064e6)
![image](https://github.com/e-m-b-a/emba/assets/34884567/e35bba19-a9d9-4997-92b2-89677ef05f98)

Screenshot to prove that results are given, I also found that `nvidia` firmware is insecure:
![image](https://github.com/e-m-b-a/emba/assets/34884567/6a778932-8a15-4414-a249-0b10ffb006d9)

Good luck!

**Comment by V33RU** [comment]
Ok using latest version of debian, thank you ..
