### ISSUE TITLE
Files not found in report

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#839]
**Describe the bug**
At the bottom of the report's menu under + Show more results the stacs_pw_hashes and common_linux_files pages are not available. Bot drops the same file not found errors in the browser.

Firefox can’t find the file at /home/seclab/Kankun/html-report//etc/stacs_pw_hashes.html.
Firefox can’t find the file at /home/seclab/Kankun/html-report//etc/common_linux_files.html.

**To Reproduce**
1. EMBA installation default mode
2. Use the firmware available here: kkeps.bin but any other should give the same result
3. Start EMBA with the following parameters: $ sudo ./emba -l ~/Kankun -f ~/kkeps.bin -t -s -z -W -X 1.0 -Y Kankun -Z Smartplug -N kkeps.bin
4. Wait the end of the scan
5. Check the "Show more results" section in the report

**Expected behavior**
Pages should be displayed, or if not applicable report' menu should not contain these items.

**Screenshots**
![kép](https://github.com/e-m-b-a/emba/assets/98665813/aff5fe64-0c71-42b9-8b9c-8449d975c355)

The same scan in EMBArk is also not OK:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/7a9f6c79-1da6-4ea6-b93f-2cc866d21dd7)

**Desktop (please complete the following information):**
- OS: e.g. Kali Linux 2023.3
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Additional context**
None.

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
Is this issue something new or is it already for a while in EMBA?

**Comment by torabi12** [comment]
It used to work. I checked some older reports and for example on 09.14. was working. Both pages were available in the report, but I don't know when it went bad.
I noticed it by accident a few days ago, because I've run a lot of tests now and all of them have these two pages wrong.

**Comment by m-1-k-3** [comment]
same here ... 
![image](https://github.com/e-m-b-a/emba/assets/497520/bff0f167-b061-4b91-a5fa-46fa332c311b)
