### ISSUE TITLE
Installation (default) fails in Ubuntu 22.04 arm64 in Parallels Desktop (on Apple Silicon)

### ISSUE THREAD

**Issue by kxynos** [e-m-b-a/emba#858]
**Describe the bug**
Installation (default) fails in Ubuntu 22.04 arm64 in Parallels Desktop (on Apple Silicon).

**To Reproduce**
1. sudo ./installer.sh -d
2. See error

**Expected behavior**
Install all packages

**Error**
```
dpkg: error processing archive external/libssl.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 external/libssl.deb
------------------------------------------------------------------------------------------------
Error detected - status code 1
Command:  echo -e "Command:  ${ORANGE}${BASH_COMMAND}${NC}"
Location:  ./installer/IF20_cve_search.sh, line 138
Stack Trace:
    [1] IF20_cve_search(): ./installer/IF20_cve_search.sh, line 138 -> IF20_cve_search
    [2] main(): ./installer.sh, line 344 -> main -d
```

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- EMBA version: current master branch (v1.3.0)
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - N

**Comment by kxynos** [comment]
ARM not supported - https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

**Comment by m-1-k-3** [comment]
Thanks for raising this issue. We will include a check in the beginning of the installation to ensure the installer will quit with a useful error message.
