### ISSUE TITLE
UEFI firmware analysis should not analyse every single file on an extracted filesystem?

### ISSUE THREAD

**Issue by brainstorm** [e-m-b-a/emba#914]
It's a bit too much (wasted?) computation to run this tool for every single file in an unpacked filesystem, isn't it?:

![image](https://github.com/e-m-b-a/emba/assets/175587/a855aaa1-a05e-4ec1-b978-9c54f03ceafd)

I'd suggest narrowing it down to relatively well known locations and offer a flag or similar to allow for deeper/broader searches?

**Comment by m-1-k-3** [comment]
will take a deeper look at this after finishing  #913

**Comment by m-1-k-3** [comment]
Which firmware have you used for testing?

**Comment by brainstorm** [comment]
The Australian one in EMBA discussions, you have a MEGA.nz download link there.

**Comment by m-1-k-3** [comment]
please check #921

**Comment by brainstorm** [comment]
Just git pulled right now, `rm -rf external results`, re-installed anew with `sudo ./installer.sh -d` but the UEFI section is still scanning irrelevant files it shouldn't scan?:

![Screenshot from 2023-12-01 19-55-25](https://github.com/e-m-b-a/emba/assets/175587/5f6f1204-697d-4baa-a54b-9f219bdf74ce)

The command I used to scan is:

```
sudo ./emba -f /home/rvalls/Desktop/Belong_Router.bin -l ./results -p ./scan-profiles/full-scan.emba
```

**Comment by m-1-k-3** [comment]
could you please check.

```
└─$ git remote show origin | grep URL
```
should show the correct EMBA repo

**Comment by brainstorm** [comment]
Ouch, my apologies, I was still in `trivy_workflow` when I did the `git pull`... 🤦🏻‍♂️ 

All good now, thanks Michael!

**Comment by m-1-k-3** [comment]
if you find further issues you are welcome :)
