### ISSUE TITLE
couldn't find remote ref master

### ISSUE THREAD

**Issue by torabi12** [e-m-b-a/emba#920]
**Describe the bug**
New installation and the update script shows this warning:

![kép](https://github.com/e-m-b-a/emba/assets/98665813/3f048f40-579f-4292-92eb-719f4077249c)

I would like to ask, after updating the CVE database, can the new database be transferred to another offline emba/EMBArk environment and how?
If I copy the `nvd-json-data-feeds` folders is it OK?

**To Reproduce**
1. EMBA installation (default mode)
2. reboot
3. ./emba_updater

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.3
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - [N]

**Comment by m-1-k-3** [comment]
> If I copy the nvd-json-data-feeds folders is it OK?

Thats the cool thing on the new mechanism. Just copy it to your new external or link from the new installation the complete external and you are good to got.

Nevertheless, I will take a look at the updater script.
