### ISSUE TITLE
Does the software have a breakpoint rescan function

### ISSUE THREAD

**Issue by Qixiao2000** [e-m-b-a/emba#974]
During the scanning process, Ubuntu 20.04 virtual machine unexpectedly shut down. Can we continue working according to the previous scanning progress?

**Comment by torabi12** [comment]
You should use supported OS as described here:
https://github.com/e-m-b-a/emba/wiki/Installation#prerequisites

Ubuntu 22.04.3 or latest Kali.

**Comment by m-1-k-3** [comment]
EMBA automatically checks the log directory. If there is an unfinished scan for the same firmware she asks you how to proceed:

![image](https://github.com/e-m-b-a/emba/assets/497520/67518eb2-6f42-4bd1-ae80-31df57d7d08a)

This feature is not fully stable and tested but works in most cases not too bad.

**Comment by m-1-k-3** [comment]
If needed, please reopen this issue.
