### ISSUE TITLE
Update minimum size requirement

### ISSUE THREAD

**Issue by Svieg** [e-m-b-a/emba#994]
**Describe the bug**

The minimum size requirement is currently at 13 GB but the current installation seems to be close to 17 GB

**To Reproduce**
1. Check available disk space (i.e. `df -h`)
2. EMBA installation (dev-mode/default mode)
3. Check available disk space again

**Expected behavior**
The sanity check for the available disk space is 13GB, I would expect 17GB as it seems to be the current installation size.

**Screenshots**

Before installation:
```
 df -h                                                                                                                                            
Filesystem      Size  Used Avail Use% Mounted on                                                                                                             
udev            3.9G     0  3.9G   0% /dev                                                                                                                   
tmpfs           794M  1.1M  793M   1% /run                                                                                                                   
/dev/sda1        78G   57G   18G  77% /    
```

After installation:
```
$ df -h                                                                                                                                    
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           794M  1.1M  793M   1% /run
/dev/sda1        78G   73G  1.3G  99% /
```

**Desktop (please complete the following information):**
- OS: Kali Linux 2023.3 rolling
- EMBA version: current master branch
- Installation method: default with up to date docker image

**Priority issue**
Are you already a [Sponsor]? - N

**Additional context**

[Sponsor]: https://github.com/sponsors/e-m-b-a

**Comment by m-1-k-3** [comment]
Thanks for reporting this issue. EMBA was damn small ... long time ago ;)
I fixed it in the upcoming PR https://github.com/e-m-b-a/emba/pull/993

**Comment by Svieg** [comment]
Great project and awesome response time, thank you!
